feldaufgaben= [
"START",
"Du stehst auf Feld 1, warte bis du nächste Runde nochmal würfeln kannst!",
"Fehlstart! Trink erstmal zwei Schluck!",
"Du stehst auf Feld 3, warte bis du nächste Runde nochmal würfeln kannst!",
"Trink zwei Schluck und erzähl einen Witz. Keinen auf Lager? Nochmal zwei Schluck!",
"Trinke zwei Schluck und ziehe ein Kleidungsstück aus!",
"Gehe 4 Felder vor!",
"Vergebe 5 Schluck an Mitspieler, zwei trinkst du!",
"Du stehst auf Feld 8, warte bis du nächste Runde nochmal würfeln kannst!",
"Alle Frauen müssen trinken!",
"Male deinem linken Nachbarn etwas auf den Arm. Falls er schon was drauf hat, trink drei Schluck!",
"Gehe ein Feld zurück!",
"Du stehst auf Feld 12, warte bis du nächste Runde nochmal würfeln kannst!",
"Sofort zurück an den Start!",
"Trinke zwei Schluck und ziehe ein Kleidungsstück aus!",
"Lass dir was auf den Arm malen! Da steht schon was? 3 mal trinken!",
"Jeder der eine Jeans anhat, trinkt zwei Schluck!",
"Jeder der noch nichts auf dem Arm stehen hat, trinkt einen!",
"Du stehst auf Feld 18, warte bis du nächste Runde nochmal würfeln kannst!",
"Endlich darfst du trinken!",
"Schnick, Schnack, Schnuck wer trinken muss! (Alle gegen alle)",
"Dein Nachbar links und rechts neben dir muss einen Schluck trinken!",
"Du stehst auf Feld 22, warte bis du nächste Runde nochmal würfeln kannst!",
"Hast du eine eins gewürfelt? Dann trink!",
"Tausche mit einem Spieler deiner Wahl dein Getränk!",
"Du darfst einem anderen Mitspieler ein Getränk mischen, welches er dann austrinken muss!",
"Der führende Spieler muss drei Schluck trinken!",
"Trink vier Schluck oder küss einen Spieler des anderen Geschlechts!",
"Alle die vor dir sind trinken!",
"Gehe vier Felder zurück",
"Du stehst auf Feld 30, warte bis du nächste Runde nochmal würfeln kannst!",
"Alle trinken zwei Schluck!",
"Finde innerhalb von 5 Sekunden einen Reim auf CfunG. Nichts eingefallen? Trink zwei Schluck!",
"Alle Spieler die hinter dir sind, trinken!",
"Gehe 3 Felder vor!",
"Es trinken alle die zwei Schluck, die ein ungerades Alter haben!",
"Ziehe ein Kleidungsstück aus!",
"Jongliere mit irgendeinem Gegestand 5 mal. Nicht geschafft? Trinke zwei Schluck!",
"Wer im Monat April oder November Geburtstag hat, muss zwei Schluck trinken!",
"Du stehst auf Feld 39, warte bis du nächste Runde nochmal würfeln kannst!",
"Halbzeit!",
"Gehe auf Feld 52!",
"Gehe 2 Felder vor!",
"Du stehst auf Feld 43, warte bis du nächste Runde nochmal würfeln kannst!",
"Male deinem rechten Nachbarn etwas auf den Arm, falls schon etwas draufsteht, trink 3 Schluck!",
"Trinke zwei Schluck und ziehe ein Kleidungsstück aus!",
"Glückspilz, musst nichts trinken!",
"Jeder, der noch nichts auf seinem Arm hat muss zwei Schluck trinken!",
"Du stehst auf Feld 48, warte bis du nächste Runde nochmal würfeln kannst!",
"Gehe 5 Felder zurück!",
"Spielt eine Runde 'Ich packe meinen Koffer'. Wer als erster versagt, trinkt zwei Schluck!",
"Sing ein Lied, wenn dir keins einfällt, trink!",
"Du stehst auf Feld 52, warte bis du nächste Runde nochmal würfeln kannst!",
"Alle trinken zwei Schluck!",
"Derjenige der bis jetzt am Wenigsten getrunken hat, trinkt zwei Schluck!",
"Bestimme einen Spieler der 3 Schlücke trinken muss!",
"Alle die eine Brille tragen, trinken zwei Schluck!",
"Endlich kannst du wieder trinken!",
"Du stehst auf Feld 58, warte bis du nächste Runde nochmal würfeln kannst!",
"Jeder der etwas auf dem Arm stehen hat, trinkt! ",
"Lies: Achtschor Achtschor achtschorn in den Achtschorn Gestockt? Trink zwei Schluck!",
"Alle mit Blonden Haaren müssen zwei Schluck trinken!",
"Such dir einen Spieler aus und male ihm etwas auf den Arm! Alle haben schon etwas auf dem Arm? Trink zwei Schluck!",
"Du stehst auf Feld 63, warte bis du nächste Runde nochmal würfeln kannst!",
"Trink und geh auf Feld 43!",
"Alle trinken!",
"Du stehst auf Feld 66, warte bis du nächste Runde nochmal würfeln kannst!",
"Zieh ein Kleidungsstück aus!",
"Derjenige der als nächstes Geburtstag hat muss zwei Schluck trinken!",
"Gehe auf Feld 30 und trink zwei Schluck!",
"Du stehst auf Feld 70, warte bis du nächste Runde nochmal würfeln kannst!",
"Addiere zur gewürfelten Augenzahl zwei. So viele Schlücke musst du trinken!",
"Wenn deine Würfelzahl gerade war trinkst du zwei Schluck, wenn sie ungerade war dann trinken alle andere zwei Schluck!",
"Versuche 20 mal auf einem Bein zu hüpfen ohne festhalten. Nicht geschafft? Trink so viele Schlücke wie dir Sprünge zu 20 gefehlt haben!",
"Trinke zwei Runden immer bevor du würfelst zwei Schluck!",
"Du stehst auf Feld 75, warte bis du nächste Runde nochmal würfeln kannst!",
"Trink drei und geh 3 Felder zurück!",
"Du stehst auf Feld 77, warte bis du nächste Runde nochmal würfeln kannst!",
"Alle außer dir müssen zwei Schluck trinken!",
"Sofort zurück an den Start!",
"ZIEL!"
]