aufgabenwahrheit = [
"In welche Person bist du verliebt?",
"Was ist das peinlichste, was dir je passiert ist?",
"Was ist deine geheimste, dunkle Fantasie?",
"Wo war dein erster Kuss?",
"Wenn du zwei Wünsche frei hättest, die nach 24 Stunden wieder verschwinden würden, was wäre das?",
"Von wem hier in der Runde würdest du dich am ehesten küssen lassen?",
"Wohin würdest du dich jetzt am liebsten beamen?",
"Wenn Du ein Tier sein könntes, welches wäre das?",
"Welche drei Dinge würdest du auf eine einsame Insel mitnehmen?",
"Was war die gemeinste Bestrafung, die du je erhalten hast und von wem für was?",
"Nach einer gewaltigen Explosion leben außer dir nur zwei Menschen des anderen Geschlechts. Wer wären die zwei und warum?",
"Was würdest du tun, wenn du für einen Tag ein Mann/eine Frau wärst?",
"Hast du schon einmal in ein Schwimmbad ins Wasser gepinkelt?",
"Was hast du zuletzt geträumt?",
"In welcher vergangenen Zeit würdest du leben wollen und warum?",
"Welchen Teil deines Körper würdest du gerne größer machen und warum?",
"Was war der größte Fehler deines Lebens?",
"Was würdest du tun, wenn du unsichtbar wärst?",
"Wer aus der Runde hat den schönsten Po?",
"Hast Du schon mal während des ersten Dates geknutscht?",
"Welches Buch ist dein Lieblingsbuch?",
"Was ist das Peinlichste, was dir bei einem Date passiert ist?",
"Was war der größte Fehler deines Lebens?",
"Hast du schon einmal eine Person des gleichen Geschlechts geküsst?",
"Wer aus der Runde, glaubst du, hat den größten Brustumfang?",
"Was ist deine schlimmste Macke?",
"Wer hat in diesem Raum den miesesten Geschmack?",
"Wen in diesem Raum magst Du am wenigsten?",
"Auf was achtest du als erstes beim anderen Geschlecht?",
"Hattest du schonmal Kontakt mit Drogen?",
"Wofür könnten die Spieler links und rechts von dir Werbung machen?",
"Wer war der Held in deiner Kindheit?",
"Welche Eigenschaft der Person zu deiner rechten magst ganz besonders?",
"Wann hast du dich zuletzt geduscht?",
"Hast Du schon mal jemanden des gleichen Geschlechts geküsst?",
"Was ist das Dümmste, das du je getan hast?",
"Wenn du morgen jemanden heiraten müsstest, wer wäre es?",
"Wann hast du zuletzt jemanden geküsst und wer war es?",
"Warst du jemals in einen Lehrer verliebt? In wen?",
"Welche Person würdest du jetzt gerne küssen?",
"Was ist das peinlichste was du besitzt?",
"Wer ist die schönste Person, die du kennst?",
"Wen aus der Runde hast du dir schonmal nackt vorgestellt?",
"Wann hattest du das letzte Mal einen Hang Over?",
"Was findest du an dem Spieler rechts von dir total blöd?",
"Wenn Du in die Runde schaust, wer wird später am meisten Geld verdienen?",
"Was war das gemeinste Gerücht, das jemals über dich in Umlauf gebracht wurde?",
"Was würdest du gerne mal ausprobieren, traust dich aber nicht?",
"Auf eine Skala von 1 - 10: Für wie gutaussehend hälst du dich?",
"Wenn du auf einer einsamen Insel strandest, mit einer CD, einem Buch und einem anderen Gegenstand, was wäre das?",
"Wenn du Gedanken lesen könntest, was wolltest du wissen?",
"Hast du in der Vergangenheit schonmal etwas gestohlen?",
"Was würdest du lieber können - Fliegen oder unsichtbar werden?",
"Was war das peinlichste Erlebnis mit einem Ex von dir?",
"Was ist das Eigenartigste, das du je gegessen oder getrunken hast?",
"Welches wirklich kindische Verhalten hast du immer noch?",
"Wie viele Jungen / Mädchen hast du schon geküsst?",
"Was ist der größte Abturner, den ein Mensch haben kann?",
"Wann hast du das letzte Mal gelogen?",
"Würdest du eine Schönheits-Operation an dir machen lassen?",
"Was ist der peinlichste Spitzname, der dir je gegeben wurde?",
"Wann hattest du das letzte Mal Sex?",
"Wann wurdest Du das letzte Mal rot und warum?",
"Mit welchem Mitspieler würdest du 1 Woche lange tauschen und warum?",
"Du ziehst auf eine einsame Insel, wen hier aus der Runde nimmst du mit?",
"Wovor hast du am meisten Angst?",
"Welchen Namen würdest du dir tätowieren lassen, wenn du müsstest?",
"Welches Tier passt am besten zu dir und warum?",
"Wo rasierst du dich überall?",
"Welche peinliche Fernsehsendung schaust du am liebsten?",
"Mit welcher berühmten Person würdest du gerne einmal eine Nacht verbringen?",
"Hast du eine Spitznamen?",
"Guckst du in die Kloschüssel bevor du spülst?",
"Welcher Film ist dein Lieblingsfilm?",
"Was war dein peinlichstes Erlebnis mit deinem Schwarm?",
"Was ist das aller Peinlichste, das dir je passiert ist?",
"Wäschst du dir immer die Hände, wenn du auf dem Klo warst?",
"Mit wem in diesem Raum würdest du überhaupt nicht gerne auf einer einsamen Insel stranden wollen? Warum nicht?",
"Wer ist deiner Meinung nach der heißeste Typ/Mädchen auf deiner Schule?",
"Hast du schon mal einen Popel gegessen?",
"Wen in diesem Raum magst du am meisten?",
"Was findest du an dir besonders schön?",
"Was ist das Dümmste, was du je getan hast?",
"In welchen Star warst du früher unsterblich verknallt?",
"Hast du schon mal einen Liebesbrief an jemanden geschrieben? Wenn ja, an wen?",
"Was würdest du gerne mal ausprobieren, traust dich aber nicht?",
"Was machst du heimlich vor dem Spiegel, wenn keiner zuschaut?",
"Hast du schon mal jemanden anderen für etwas beschuldigt, obwohl DU schuld warst?",
"Würdest du die Person rechts neben dir für 50 Euro küssen?",
"Welche Person in dieser Runde sollte unbedingt zum Friseur gehen?",
"Welcher war der ungewöhnlichste Ort, an dem du mal pinkeln musstest?",
"Was würdest du eher trinken: Urin, der nach Orangensaft schmeckt, oder Orangensaft, der nach Urin schmeckt?",
"Von wie vielen Jungs/Mädchen hast du schon einen Korb gekriegt?",
"Wurdest du schon mal nachts geweckt, weil du so nervig geschnarcht hast?",
"Was ist dein peinlichster Lieblings-Song?",
"Wer hat dir den schlimmsten Liebeskummer bereitet?",
"Guckst du in die Kloschüssel, bevor du spülst?",
"Hast du schon mal Chat-Verläufe mit einer Person in diesem Raum gescreenshottet und an jemand anderen weitergeschickt?",
"Faltest du oder rollst du das Klopapier, wenn du auf Toilette bist?",
"Hast du Bilder von einer Person in diesem Raum auf deinem Handy, ohne dass er/sie davon weiß?",
"Wen findest du in der Runde am schönsten? Sortiere alle Leute von hübsch nach hässlich.",
"Wen aus deiner Klasse würdest du am ehesten küssen?",
"Wen aus dieser Runde würdest du bei der nächsten Party NICHT einladen?",
"Was war die letzte Lüge, die du der Person rechts von dir erzählt hast?",
"Was war dein größter Wunsch, den du nie ausgesprochen hast?",
"Welche Straftat hast du schon begangen?",
"Pinkelst du unter der Dusche?",
"Welches kindische Verhalten hast du heute noch?",
"Wo rasierst du dich überall?",
"Hast du schon mal jemanden betrogen?",
"Was ist deine größte Angst, von der niemand etwas weiß?",
"In wen warst du schon mal verliebt, von dem keiner etwas weiß?",
"Hast du schon mal deinen BH oder deine Unterhose ausgestopft?",
"Wärst du lieber hässlich und beliebt oder hübsch und unbeliebt?",
"Welche Stellung findest du am besten?",
"Schicke ein Selfie mit Kussmund an deine/n Ex",
"Rufe bei Burger King an und frage, wo der nächste McDonald's ist",
"Lass dich von der Person rechts schminken. Ihm/ihr werden die Augen verbunden!",
"Geh an den Kühlschrank. Breche alle noch geschlossenen Packungen an und lass sie halb angegessen stehen.",
"Stecke deinen Arm zehn Sekunden lang ins Klo.",
"Male dir eine Mono-Braue und poste dann ein Selfie auf Insta.",
"Ruf deine Mutter an und sag, dass du ein Kind bekommst.",
"Berühre die Zunge des Gegenübers mit deiner Zunge für zehn Sekunden.",
"Schreibe in der ersten WhatsApp-Gruppe, die du findest: Ich habe keine Lust mehr auf euch!",
"Erkläre in der Instagram-Story, warum dich alle deine Follower nerven.",
"Trinke einen Shot Olivenöl.",
"Führe ein Dialog mit einem Gegenstand und tu so, als würdet ihr euch streiten.",
"Überrasche dein Gegenüber mit einem Lapdance.",
"Gib der Person links von dir einen Kuss auf den Po.",
"Zeige der Runde deinen letzten WhatsApp-Chat.",
"Wie oft hast du schon geküsst?",
"Was ist das peinlichste das dir je passiert ist?",
"Wie viele Typen / Mädchen hast du schon geküsst?",
"In wen bist du verliebt?",
"Welchen Star findest du heiß?",
"Würdest du was mit XY (Name einfügen) anfangen?",
"Hast du schon mal was geklaut?",
"Welches Tier passt am besten zu dir und warum?",
"Was war dein schlechtestes Date?",
"Wen würdest du jetzt gerne küssen?",
"Was ist deine geheimste, dunkle Fantasie?",
"Würdest du lieber deinen Po tätowieren oder deine Zunge piercen lassen?",
"Mit welcher berühmten Person würdest du gerne einmal deine Nacht verbringen?",
"Wohin würdest du dich jetzt am liebsten beamen? ",
"Du musst einen Star heiraten, wen? ",
"Wie/wo/mit wem war dein erster Kuss?",
"In welche Person bist du verliebt?",
"Hast du schon einmal in ein Schwimmbad ins Wasser gepinkelt?",
"Wenn Du ein Tier sein könntes, welches wäre das?",
"Schnarchst du nachts?",
"Wer hat dir den schlimmsten Liebeskummer bereitet?",
"In welche Person bist du verliebt?",
"Was hast du zuletzt geträumt?",
"Hattest du schonmal Kontakt mit Drogen?",
"Was ist der größte Abturner, den ein Mensch haben kann?",
"Warst du jemals in einen Lehrer verliebt?",
"Hast du einen 2.Spitznamen?",
"Wer ist die schönste Person, die du kennst?",
"Guckst du in die Kloschüssel bevor du spülst?",
"Hast du schon mal heimlich geraucht?",
"Was war die gemeinste Bestrafung?",
"Wann war dein erster Kuss?",
"Wie oft hast du schon jemanden geküsst?",
"Hattest du schon  Mal einen Hang Over?",
"Vor was hast du am meisten Angst?",
"Was ist dein Lieblingsfilm?",
"Welchen Namen würdest du dir tätowieren lassen?",
"Wer war der Held in deiner Kindheit?",
"Welche Person würdest du jetzt gerne küssen?",
"Was ist dein Lieblingsbuch?",
"Was war der größte Fehler deines Lebens?",
"Würdest du eine Schönheits-Op an dir machen lassen?",
"Was würdest du gerne mal ausprobieren?",
"Welche Fernsehsendung schaust du am liebsten?",
"Was war dein peinlichstes Erlebnis?",
"Hast du  schonmal etwas gestohlen?",
"Wann hast du dich zuletzt geduscht?",
"Was ist deine schlimmste Macke?",
"Welcher Mitspieler hat die schönsten Hände?",
"Wen würdest du auf eine einsame Insel mitnehmen?",
"Wo war dein erster Kuss?",
"Wann hast du das letzte Mal gelogen?",
"Wann war dein erstes Mal?",
"Bist du noch Jungfrau?",
"Hast du schonmal jemanden betrogen?",
"Was war dein schlimmster Korb?",
"Stöhnst du beim Orgasmus?",
"Wurdest du schonmal bei der Selbstbefriedigung erwischt?",
"Hast du jemals deinen BH ausgestopft?",
"Wann hattest du das letzte mal Sex?",
"An welchen Orten hast du bereits masturbiert?",
"Woran denkst du, wenn du dich selbst befriedigst?",
"Hast du Erfahrung mit Natursekt?",
"Hattest du schonmal Sex im Freien?",
"Was ist deine Lieblingsstellung?",
"Warst du immer treu?",
"Welche Schamhaarfrisur hast du?",
"Warst du schonmal intim mit 2 Personen gleichzeitig?",
"Was ist deine geheimste, dunkle Fantasie?",
"Würdest du dir von einem Mann ins Gesicht spritzen lassen?",
"Hast du, als du jünger warst, Doktorspiele gespielt?",
"Hast du bereits homosexuelle Erfahrungen gemacht?",
"Hattest du schonmal Telefonsex?",
"Wenn du eine Erotik-Kontaktanzeige aufgeben müsstest, wie würde sie lauten?",
"Hattest du einen Teenieschwarm?",
"In welche Person bist du verliebt?",
"Mit welchem Star hättest du gerne mal ein Date?",
"Was ist der peinlichste Moment in deinem Leben?",
"Welchen Mund findest du aus der Gruppe hier am schönsten?",
"Welcher Mitspieler hat die schönsten Hände?",
"Wo war dein erster Kuss?",
"Von wem hier in der Runde würdest du dich am ehesten küssen lassen?",
"Wer hier am Tisch ist wohl am kitzeligsten?",
"Was war der größte Fehler deines Lebens?",
"Ist dir bei einem Date schonmal etwas Peinliches passiert?",
"Hattest du schonmal Kontakt mit Drogen?",
"Welche Person würdest du jetzt gerne küssen?",
"Wann hattest du das letzte Mal einen Hang Over?",
"Hast du schonmal bei einer Schulprüfung geschummelt?",
"Welche(n) Lehrer(in) findest du scharf?",
"Hast du in der Vergangenheit schonmal etwas gestohlen?",
"Schnarchst du nachts?",
"Welches ist dein Lieblings-Song?",
"Mit welchem Mitspieler würdest du 1 Woche lange tauschen und warum?",
"Du ziehst auf eine einsame Insel, wen hier aus der Runde nimmst du mit?",
"Vor was hast du am meisten Angst?",
"Wo rasierst du dich überall?",
"Hast du eine Spitznamen?",
"Guckst du in die Kloschüssel bevor du spülst?",
"Wer hat dir den schlimmsten Liebeskummer bereitet? ",
"Was ist deine Lieblingsstellung?",
"Wo ist deine erogene Zone?",
"Stöhnst du beim Höhepunkt?",
"Mit wem hier hättest du gerne Sex?",
"Wann hattest du das letzte mal Sex?",
"Wo hast du Intimpiercings?",
"Wieviele Männer / Frauen hast du schon geküsst?",
"Was war dein schlimmster Korb?",
"Mit wem hattest du das heißeste Date?",
"Welche Stellung ist deine liebste?",
"Wann war dein erstes Mal?",
"Bist du noch Jungfrau?",
"Auf der Toilette: Faltest oder rollst du das Klopapier?",
"Wo rasierst du dich überall?",
"Warst du schonmal intim mit 2 Personen gleichzeitig?",
"Hast du deine Schwester / deinen Bruder schonmal stöhnen hören?",
"Wurdest du schonmal bei der Selbstbefriedigung erwischt?",
"An welchen Orten hattest du schonmal Sex?",
"Hast du schonmal jemanden betrogen?",
"Bist du immer treu?"
]


aufgabenpflicht = [
"Gib einem Mitspieler deiner Wahl einen Kuss auf den Mund",
"Gib deinem Mitspieler zu deiner rechten einen Kuss",
"Halte 5 Minuten Händchen mit einer Person deiner Wahl",
"Benimm dich zwei Minuten wie ein Huhn",
"Tausche die Klamotten mit dem Mitspieler rechts von dir",
"Erzähle der Person gegenüber, was seine Vorzüge und Macken sind",
"Imitiere ein Tier deiner Wahl",
"Mach dich im spiegel selbst an",
"Spiele Dieter Bohlen und gib für 2 Runden zu allem Kommentare ab",
"Lass dir von einem Mitspieler eine Frisur stylen",
"Füttere die Person rechts neben dir mit etwas Leckerem",
"Veranstalte einen Catwalk wie bei Germany’s next Top Model",
"Zeig deinen Mitspielern wie ein perfekter Zungenkuss aussieht - aber alleine",
"Spreche 2 Runden lang nur englisch",
"Massiere einem Mitspieer deiner Wahl die Füße",
"Täusche einen totalen Lachkrampf vor",
"Tu so, als würdest du ein kind gebären",
"Trage den BH von einer anderen Person",
"Rappe über einen Mitspieler",
"Sprich die nächsten 3 Minuten in Babysprache",
"Lecke einen Gegenstand in Greifnähe ab",
"Laufe einmal um die Gruppe herum und belle wie ein Hund",
"Ziehe ein Kleidungsstück aus; Alle anderen müssen es auch ausziehen",
"Versuche, für 10 Sekunden zu breakdancen",
"Mache die lustigste Grimasse, die dir einfällt",
"Spiele eine Sterbeszene",
"Zeig allen, wie der Moonwalk von Michael Jackson geht",
"Mach einen Bauchtanz für 1 Minute",
"Tanze wie eine Ballerina",
"Lass jemand anders deine gespeicherten WhatsApp Nachrichten lesen",
"Zeige der Gruppe ein wirklich peinliches Foto von dir",
"Kratze dich mit deinem großen Zeh unter der Achsel",
"Mach der Person links von dir einen romantischen Heiratsantrag",
"Rede 3 Runden mit einem Akzent",
"Gib allen anwesenden Frauen einen Kuss auf die Wange",
"Spiele einen Orgasmus vor",
"Sing während du Liegestütze machst laut alle meine Entchen",
"Erkläre der Person rechts von dir, warum du eine Bestrafung verdienst",
"Tausche das T-Shirt mit der Person rechts von dir",
"Strecke deinen nackten Hintern aus dem Fenster",
"Mache der Person links neben dir für 2 Minuten lang alles nach",
"Tausch die Kleider mit dem Mitspieler direkt gegenüber",
"Nenne eine Sache über dich, wegen der du schon Komplimente bekommen hast",
"Gib einem Mitspieler eine 2 Minuten Kopfmassage",
"Tu so als hättest du eine gespaltene Persönlichkeit und streite mit dir selbst",
"Trage deine Kleidung auf links",
"Mach ein ugly Selfie von dir und poste es bei Facebook",
"Simuliere mit einer Flasche einen Zungenkuss",
"Lass dich von einem anderen Mitspieler schminken",
"Trage die Person links von dir einmal durch den Raum",
"Spiele eine Szene aus deinem Lieblingsfilm nach",
"Mach 10 Liegestütze",
"Versuche deine Beine hinter den Kopf zu bekommen",
"Iss einen Löffel Mehl",
"Simuliere einen Affen für 1 Runde",
"Versuch einen Zeh in den Mund zu nehmen",
"Spiel eine Domina",
"Zeige den anderen ein wirklich peinliches Foto von dir",
"Iss nur noch etwas ohne deine Hände zu benutzen",
"Iss etwas und tue so, als wäre es das leckerste, was du je gegessen hast",
"Spiele 1 Runde lang den Gollum aus Herr der Ringe",
"Spiele einen Wutanfall",
"Der Spieler links von dir darf dir ein Gebräu aus allen möglichen Zutaten mischen und du musst es trinken",
"Pose 1 Minute wie ein Bodybuilder",
"Trage einen Turban aus Toilettenpapier",
"Schnapp dir Schminkzeug und schminke die Person rechts neben dir",
"Lass dich von anderen an einen Stuhl fesseln",
"Ruf einen Kontakt aus Deinem Handy an und stöhne ins Telefon",
"Imitiere eine Person deiner Wahl aus dieser Gruppe",
"Mach einem Gegenstand eine Liebeserklärung",
"Iss Katzen- oder Hundefutter",
"Taste die Person rechts von dir ab",
"Sag 3x hintereinander ganz schnell einen Zungenbrecher auf",
"Ruf jemanden an und wünsche ihm ein frohes neues Jahr",
"Bettle die Person dir gegenüber an, dir den Hintern zu versohlen",
"Stelle innerhalb 1 Minute fest, wessen Haare am besten duften",
"Hüpfe wie ein Frosch quakend durch den Raum",
"Tanz zu dem Lied, was grade gespielt wird",
"Schreibe mit einem Stift deinen Namen, benutze dabei jedoch deinen Fuß",
"Versuche mit der Zungenspitze deine Nase zu berühren",
"Iss einen Keks und pfeife nebenbei ein Lied",
"Versuche wie Nicki Minaj (oder ein anderer Rapper) zu rappen!",
"Rede drei Runden mit einem Akzent!",
"Spiele eine Szene aus deinem Lieblingsfilm nach!",
"Führe eine Unterhaltung mit einem Stuhl und tu so, als ob er antworten würde.",
"Mach Miley Cyrus' Bühnen-Auftritt bei den VMA’s nach!",
"Flirte einen Mitspieler an, so als wäre er/sie der heißeste Typ/Mädel, den du je gesehen hast. Gib alles!",
"Erzähle der Person direkt gegenüber, was toll an ihm/ihr ist!",
"Tu so, als würdest du dich gerade bei Germanys Next Top Model bewerben und den Laufsteg vor Heidi und Co. hoch und runter laufen!",
"Du musst dich von den anderen Mitspielern schminken lassen!",
"Tu so, als wärst du der absolute Kussexperte und zeig deinen Mitspielern, wie ein perfekter Zungenkuss aussieht – aber alleine!",
"Mach jemanden aus der Runde pantomimisch nach. Die anderen müssen erraten, wer es ist!",
"Du darfst drei Runden lange nicht die Buchstaben E oder A aussprechen.",
"Gib allen Mädchen in dem Raum einen Kuss auf die Wange.",
"Tausche ein Klamotten-Teil mit dem Mitspieler links von dir.",
"Spiele das letzte Lied, das du auf dem Handy gehört hast, ab und tanze wild dazu.",
"Zeig deinen Mitspielern, welches Bild du als letztes bei WhatsApp verschickt hast.",
"Du musst innerhalb einer Minute herausfinden, wer in der Runde die am besten duftenden Haare hat.",
"Immer, wenn du etwas sagen willst, musst du vorher eine Grimasse ziehen.",
"Poste ein Bild deiner Füße in deiner Insta-Story.",
"Pose 30 Sekunden lang wie ein Bodybuilder.",
"Du musst fünf Minuten lang mit der Person deiner Wahl Händchen halten.",
"Mache der Person rechts von dir einen ganz romantischen Heiratsantrag.",
"Schicke der letzten Person, mit der du auf WhatsApp geschrieben hast, ein Grimassen-Selfie.",
"Du darfst die nächste halbe Stunde nur etwas essen ohne deine Hände zu benutzen.",
"Poste ein Bild von der Person links von dir auf Instagram und schreibe dazu: Er/sie ist mega hot!!!",
"Kuss auf die Wange/den Mund eine anders geschlechtliche Person",
"Bauch/Sixpack zeigen",
"Deinen gegenüber Umarmen",
"5 Minuten Händchen halten",
"Tausche das T-Shirt mit der Person rechts/links von dir",
"Aus dem Fenster schreien Ich heiße .. und bin ein Esel",
"Boden ablecken",
"Füttere die Person rechts neben dir mit etwas Leckerem",
"Trinke ein großes Glas Cola auf Ex",
"Gähne und versuche min. 1 Person dadurch auch zum Gähnen zu bringen. ",
"Mache 5 Liegestützen",
"Lass dir von dem Mitspieler links eine krasse Frisur stylen.",
"Erzähle der Person gegenüber, wie toll er/sie ist. ",
"Nenne eine Sache über dich, wegen der du schon Komplimente bekommen hast ",
"Beschreibe deinen schlimmsten aktuellen Lehrer ",
"Iss etwas und tue so, als wäre es das leckerste, was du je gegessen hast",
"Mache die lustigste Grimasse, die dir einfällt",
"Mache Furzgeräusche ",
"Ruf einen Freund an, und sage, du seist schwanger",
"Finde heraus, wessen Haare am besten riechen",
"Küsse die anders geschlechtliche Person, die als erstes rechts von dir kommt",
"Zeige deine Armmuskeln ",
"Wirf der Person links neben dir einen verführerischen Blick zu",
"Gib der Person, die 2 Plätze weiter rechts sitzt einen Bussi auf die Wange",
"Benimm dich zwei Minuten wie ein Huhn ",
"Mach einen Lehrer deiner Wahl nach ",
"Der Spieler rechts von dir darf dir ein Gebräu aus allen möglichen Zutaten mischen und du musst es trinken ",
"Bist du noch Jungfrau?",
"Rasierst du dich? Wenn ja,wo?",
"Welche Frisur hast du im Intimbereich?",
"Bist du neugierig darauf intim mit einer Person deines eigenen Geschlechts zu werden?",
"Liebst du ein langes Vorspiel? Wenn ja, wie sollte es aussehen? ",
"Woran denkst du, wenn du dich selbst befriedigst?",
"Ziehe dein Oberteil aus. Frauen auch den BH.",
"Mach es deinem Partner mit seiner/ihrer Hand.",
"Lecke die Brustwarzen von deinem Partner.",
"Verbinde deinem Partner die Augen und verwöhne ihn.",
"Strippe für deinen Partner. Wenn du schon nackt bist, zieh dich wieder an und strippe dann.",
"Der Mitspieler rechts von dir öffnet dir alle Knöpfe und Reißverschlüsse.",
"Simuliere einen Affen für 1 Runde",
"Küsse deinen Nachbarn",
"Tanze wie eine Ballerina",
"Spreche 2 runden lang nur Russisch",
"Trage deine Kleidung auf links",
"Tanz zu dem Lied, was grade gespielt wird",
"Mach 10 Liegestütze",
"Imitiere eine Person deiner Wahl ",
"Iss einen Löffel Zimt",
"Simuliere mit einer Flasche einen Zungenkuss",
"Gebe der Flasche einen Zungenkuss",
"Gib einem Mitspieler eine 2 Minuten Kopfmassage",
"Spiele einen Orgasmus vor",
"Mach einen Bauchtanz für 1 Minute",
"Zeige der Runde deinen nackten Bauch",
"Pose 2 Minute wie ein Bodybuilder",
"Massiere deinem Mitspieler  die Füsse ",
"Zeige  ein wirklich peinliches Foto von dir",
"Iss einen Löffel Hundefutter",
"Spiele einen Wutanfall vor",
"Trage den BH von einer anderen Person",
"Imitiere ein Tier deiner Wahl",
"Mach der Person rechts von dir einen romantischen Heiratsantrag",
"Sing  laut alle meine Entchen",
"Ruf deine Eltern von Deinem Handy an und stöhne ins Telefon",
"Ruf jemanden an und wünsche ihm Frohe Weihnachten",
"Hüpfe wie ein Frosch quakend durch den Raum",
"Versuche mit der Zungenspitze deine Nase zu berühren",
"Sag 5x hintereinander ganz schnell einen Zungenbrecher auf",
"Strecke deinen nackten Hintern aus dem Fenster",
"Ziehe dein Oberteil aus – Frauen auch den BH",
"Spucke auf deine Brustwarzen und massiere sie damit",
"Imitiere einen Exhibitionisten",
"Verbringe die nächste Spielrunde nackt",
"Trink dein nächstes Getränk auf Ex",
"Spiele einen Orgasmus vor",
"Mache einen Striptease",
"Bestimme einen Mitspieler, der dir in die Hose greifen muss",
"Nimm eine Banane oder Gurke und simuliere den perfekten BlowJob",
"Gib dem Spieler dir gegenüber einen Zungenkuss",
"Ziehe dich aus und erkläre den anderen Mitspielern die Vorzüge deiner Geschlechtsteile",
"Massiere deine eigene Brust auf erotische Weise",
"Erzähle eine schmutzige Geschichte",
"Rufe eine fremde Person an und biete Telefonsex an",
"Beschreibe dein Geschlechtsteil wie ein Produkt",
"Pinkel vom Balkon",
"Sprüh Sahne auf deine Brust und lass sie von einem Mitspieler ablecken",
"Gib einem Mitspieler deiner Wahl einen Kuss auf den Mund",
"Gib deinem Mitspieler zu deiner rechten einen Kuss",
"Zeige der Runde deinen nackten Bauch",
"Halte 5 Minuten Händchen mit einer Person deiner Wahl",
"Lass dir von einem Mitspieler eine Frisur stylen",
"Veranstalte einen Catwalk wie bei Germany’s next Top Model",
"Spreche 2 runden lang nur englisch",
"Einem Mitspieler deiner Wahl die Füsse massieren",
"Mach einen Bauchtanz für 1 Minute",
"Mache der Person links von Dir einen romantischen Heiratsantrag",
"Gib allen anwesenden Frauen einen Kuss auf die Wange",
"Tausch die Kleider mit dem Mitspieler direkt gegenüber",
"Gib einem Mitspieler eine 2 Minuten Kopfmassage",
"Simuliere einen Affen für 1 Runde",
"Immer wenn du etwas gefragt wirst, ziehe zuerst eine Grimasse",
"Iss nur noch etwas ohne die Hände zu benutzen",
"Spiele 1 Runde lang den Gollum aus Herr der Ringe",
"Füttere einen beliebigen Spieler mit einer Knabberei",
"Pose 1 Minute wie ein Bodybuilder",
"Stelle binnen 1 Minute fest, wessen Haare am besten duften",
"Tanz zu dem Lied, was grade gespielt wird",
"Veranstalte eine Striptease",
"Gib einem Mitspieler einen Kuss auf den nackten Po",
"Nimm eine Banane oder Gurke und simuliere den perfekten BlowJob",
"Trink dein nächstes Getränk auf Ex",
"Klingel in Unterwäsche bekleidet bei deinem Nachbarn und entschuldige dich für den Lärm",
"Verpasse einem Mitspieler einen Knutschfleck",
"Führe ein erotisches Gespräch mit einem Mitspieler deiner Wahl"
]