var aufgabenaeltere = [
						"Kuss auf die Wange/den Mund eine anders geschlechtliche Person",
						"Bauch/Sixpack zeigen",
						"Deinen gegenüber Umarmen",
						"5 Minuten Händchen halten",
						"Tausche das T-Shirt mit der Person rechts/links von dir",
						"Aus dem Fenster schreien: Ich heiße .. und bin ein Esel",
						"Boden ablecken",
						"Füttere die Person rechts neben dir mit etwas Leckerem",
						"Trinke ein großes Glas Cola auf Ex",
						"Gähne und versuche min. 1 Person dadurch auch zum Gähnen zu bringen.", 
						"Mache 5 Liegestützen",
						"Lass dir von dem Mitspieler links eine krasse Frisur stylen.",
						"Erzähle der Person gegenüber, wie toll er/sie ist.",
						"Nenne eine Sache über dich, wegen der du schon Komplimente bekommen hast ",
						"Beschreibe deinen schlimmsten aktuellen Lehrer", 
						"Iss etwas und tue so, als wäre es das leckerste, was du je gegessen hast",
						"Mache die lustigste Grimasse, die dir einfällt",
						"Mache Furzgeräusche",
						"Ruf einen Freund an, und sage, du seist schwanger",
						"Finde heraus, wessen Haare am besten riechen",
						"Küsse die anders geschlechtliche Person, die als erstes rechts von dir kommt",
						"Zeige deine Armmuskeln",
						"Wirf der Person links neben dir einen verführerischen Blick zu",
						"Gib der Person, die 2 Plätze weiter rechts sitzt einen Bussi auf die Wange",
						"Benimm dich zwei Minuten wie ein Huhn",
						"Mach einen Lehrer deiner Wahl nach",
						"Der Spieler rechts von dir darf dir ein Gebräu aus allen möglichen Zutaten mischen und du musst es trinken",
						"Wie oft hast du schon geküsst?",
						"Was ist das peinlichste das dir je passiert ist?",
						"Wie viele Typen / Mädchen hast du schon geküsst?",
						"In wen bist du verliebt?",
						"Welchen Star findest du heiß?",
						"Würdest du was mit XY (Name einfügen) anfangen?",
						"Hast du schon mal was geklaut?",
						"Welches Tier passt am besten zu dir und warum?",
						"Was war dein schlechtestes Date?",
						"Wen würdest du jetzt gerne küssen?",
						"Was ist deine geheimste, dunkle Fantasie?",
						"Würdest du lieber deinen Po tätowieren oder deine Zunge piercen lassen?",
						"Mit welcher berühmten Person würdest du gerne einmal deine Nacht verbringen?",
						"Wohin würdest du dich jetzt am liebsten beamen? ",
						"Du musst einen Star heiraten, wen? ",
						"Wie/wo/mit wem war dein erster Kuss?",
						"Was ist das aller Peinlichste, das dir je passiert ist?",
						"Wer aus der Runde hat den schönsten Po?",
						"Wäschst du dir immer die Hände, wenn du auf dem Klo warst?",
						"Mit wem in diesem Raum wolltest du überhaupt nicht auf einer einsamen Insel stranden? Warum nicht?",
						"Wer ist der heißeste Typ/ Mädchen auf deiner Schule?",
						"Hast du schon mal einen Popel gegessen?",
						"Wenn du mit einem Lehrer ausgehen müsstest, wer wäre das? Wie würde euer Date aussehen?",
						"Wen in diesem Raum magst du am meisten?",
						"Findest du dich selber sexy?",
						"Was ist das Dümmste, was du je getan hast?",
						"In welchen Star warst du früher unsterblich verknallt?",
						"Hast du schon mal einen Liebesbrief an jemanden geschrieben? Wenn ja, an wen?",
						"Was würdest du gerne mal ausprobieren, traust dich aber nicht?",
						"In welche Person bist du verliebt?",
						"Was ist das peinlichste, was dir je passiert ist?",
						"Was ist deine geheimste, dunkle Fantasie?",
						"Wo war dein erster Kuss?",
						"Wenn du zwei Wünsche frei hättest, die nach 24 Stunden wieder verschwinden würden, was wäre das?",
						"Von wem hier in der Runde würdest du dich am ehesten küssen lassen?",
						"Wohin würdest du dich jetzt am liebsten beamen?",
						"Wenn Du ein Tier sein könntes, welches wäre das?",
						"Welche drei Dinge würdest du auf eine einsame Insel mitnehmen?",
						"Was war die gemeinste Bestrafung, die du je erhalten hast und von wem für was?",
						"Nach einer gewaltigen Explosion leben außer dir nur zwei Menschen des anderen Geschlechts. Wer wären die zwei und warum?",
						"Was würdest du tun, wenn du für einen Tag ein Mann/eine Frau wärst?",
						"Hast du schon einmal in ein Schwimmbad ins Wasser gepinkelt?",
						"Was hast du zuletzt geträumt?",
						"In welcher vergangenen Zeit würdest du leben wollen und warum?",
						"Welchen Teil deines Körper würdest du gerne größer machen und warum?",
						"Was war der größte Fehler deines Lebens?",
						"Was würdest du tun, wenn du unsichtbar wärst?",
						"Wer aus der Runde hat den schönsten Po?",
						"Hast Du schon mal während des ersten Dates geknutscht?",
						"Welches Buch ist dein Lieblingsbuch?",
						"Was ist das Peinlichste, was dir bei einem Date passiert ist?",
						"Was war der größte Fehler deines Lebens?",
						"Hast du schon einmal eine Person des gleichen Geschlechts geküsst?",
						"Wer aus der Runde, glaubst du, hat den größten Brustumfang?",
						"Was ist deine schlimmste Macke?",
						"Wer hat in diesem Raum den miesesten Geschmack?",
						"Wen in diesem Raum magst Du am wenigsten?",
						"Auf was achtest du als erstes beim anderen Geschlecht?",
						"Hattest du schonmal Kontakt mit Drogen?",
						"Wofür könnten die Spieler links und rechts von dir Werbung machen?",
						"Wer war der Held in deiner Kindheit?",
						"2Welche Eigenschaft der Person zu deiner rechten magst ganz besonders?",
						"Wann hast du dich zuletzt geduscht?",
						"Hast Du schon mal jemanden des gleichen Geschlechts geküsst?",
						"Was ist das Dümmste, das du je getan hast?",
						"Wenn du morgen jemanden heiraten müsstest, wer wäre es?",
						"Wann hast du zuletzt jemanden geküsst und wer war es?",
						"Warst du jemals in einen Lehrer verliebt? In wen?",
						"Welche Person würdest du jetzt gerne küssen?",
						"Was ist das peinlichste was du besitzt?",
						"Wer ist die schönste Person, die du kennst?",
						"Wen aus der Runde hast du dir schonmal nackt vorgestellt?",
						"Wann hattest du das letzte Mal einen Hang Over?",
						"Was findest du an dem Spieler rechts von dir total blöd?",
						"Wenn Du in die Runde schaust, wer wird später am meisten Geld verdienen?",
						"Was war das gemeinste Gerücht, das jemals über dich in Umlauf gebracht wurde?",
						"Was würdest du gerne mal ausprobieren, traust dich aber nicht?",
						"Auf eine Skala von 1 - 10: Für wie gutaussehend hälst du dich?",
						"Wenn du auf einer einsamen Insel strandest, mit einer CD, einem Buch und einem anderen Gegenstand, was wäre das?",
						"Wenn du Gedanken lesen könntest, was wolltest du wissen?",
						"Hast du in der Vergangenheit schonmal etwas gestohlen?",
						"Was würdest du lieber können - Fliegen oder unsichtbar werden?",
						"Was war das peinlichste Erlebnis mit einem Ex von dir?",
						"Was ist das Eigenartigste, das du je gegessen oder getrunken hast?",
						"Welches wirklich kindische Verhalten hast du immer noch?",
						"Wie viele Jungen / Mädchen hast du schon geküsst?",
						"Was ist der größte Abturner, den ein Mensch haben kann?",
						"Wann hast du das letzte Mal gelogen?",
						"Würdest du eine Schönheits-Operation an dir machen lassen?",
						"Was ist der peinlichste Spitzname, der dir je gegeben wurde?",
						"Wann hattest du das letzte Mal Sex?",
						"Wann wurdest Du das letzte Mal rot und warum?",
						"Mit welchem Mitspieler würdest du 1 Woche lange tauschen und warum?",
						"Du ziehst auf eine einsame Insel, wen hier aus der Runde nimmst du mit?",
						"Wovor hast du am meisten Angst?",
						"Welchen Namen würdest du dir tätowieren lassen, wenn du müsstest?",
						"Welches Tier passt am besten zu dir und warum?",
						"Wo rasierst du dich überall?",
						"Welche peinliche Fernsehsendung schaust du am liebsten?",
						"Mit welcher berühmten Person würdest du gerne einmal eine Nacht verbringen?",
						"Hast du eine Spitznamen?",
						"Guckst du in die Kloschüssel bevor du spülst?",
						"Welcher Film ist dein Lieblingsfilm?",
						"Was war dein peinlichstes Erlebnis mit deinem Schwarm?",
						"Mitspieler dürfen sich eine Aufgabe aussuchen",
						"Gib einem Mitspieler deiner Wahl einen Kuss auf den Mund",
						"Gib deinem Mitspieler zu deiner rechten einen Kuss",
						"Halte 5 Minuten Händchen mit einer Person deiner Wahl",
						"Benimm dich zwei Minuten wie ein Huhn",
						"Tausche die Klamotten mit dem Mitspieler rechts von dir",
						"Erzähle der Person gegenüber, was seine Vorzüge und Macken sind",
						"Imitiere ein Tier deiner Wahl",
						"Mach dich im spiegel selbst an",
						"Spiele Dieter Bohlen und gib für 2 Runden zu allem Kommentare ab",
						"Lass dir von einem Mitspieler eine Frisur stylen",
						"Füttere die Person rechts neben dir mit etwas Leckerem",
						"Veranstalte einen Catwalk wie bei Germany’s next Top Model",
						"Zeig deinen Mitspielern wie ein perfekter Zungenkuss aussieht - aber alleine",
						"Spreche 2 Runden lang nur englisch",
						"Massiere einem Mitspieer deiner Wahl die Füße",
						"Täusche einen totalen Lachkrampf vor",
						"Tu so, als würdest du ein kind gebären",
						"Trage den BH von einer anderen Person",
						"Rappe über einen Mitspieler",
						"Sprich die nächsten 3 Minuten in Babysprache",
						"Lecke einen Gegenstand in Greifnähe ab",
						"Laufe einmal um die Gruppe herum und belle wie ein Hund",
						"Ziehe ein Kleidungsstück aus; Alle anderen müssen es auch ausziehen",
						"Mache die lustigste Grimasse, die dir einfällt",
						"Spiele eine Sterbeszene",
						"Zeig allen, wie der Moonwalk von Michael Jackson geht",
						"Mach einen Bauchtanz für 1 Minute",
						"Tanze wie eine Ballerina",
						"Lass jemand anders deine gespeicherten WhatsApp Nachrichten lesen",
						"Zeige der Gruppe ein wirklich peinliches Foto von dir",
						"Kratze dich mit deinem großen Zeh unter der Achsel",
						"Mach der Person links von dir einen romantischen Heiratsantrag",
						"Rede 3 Runden mit einem Akzent",
						"Gib allen anwesenden Frauen einen Kuss auf die Wange",
						"Spiele einen Orgasmus vor",
						"Sing während du Liegestütze machst laut alle meine Entchen",
						"Erkläre der Person rechts von dir, warum du eine Bestrafung verdienst",
						"Tausche das T-Shirt mit der Person rechts von dir",
						"Strecke deinen nackten Hintern aus dem Fenster",
						"Mache der Person links neben dir für 2 Minuten lang alles nach",
						"Tausch die Kleider mit dem Mitspieler direkt gegenüber",
						"Nenne eine Sache über dich, wegen der du schon Komplimente bekommen hast",
						"Gib einem Mitspieler eine 2 Minuten Kopfmassage",
						"Tu so als hättest du eine gespaltene Persönlichkeit und streite mit dir selbst",
						"Trage deine Kleidung auf links",
						"Mach ein ugly Selfie von dir und poste es bei Facebook",
						"Simuliere mit einer Flasche einen Zungenkuss",
						"Lass dich von einem anderen Mitspieler schminken",
						"Trage die Person links von dir einmal durch den Raum",
						"Mach 10 Liegestütze",
						"Versuche deine Beine hinter den Kopf zu bekommen",
						"Iss einen Löffel Mehl",
						"Simuliere einen Affen für 1 Runde",
						"Versuch einen Zeh in den Mund zu nehmen",
						"Spiel eine Domina",
						"Zeige den anderen ein wirklich peinliches Foto von dir",
						"Iss nur noch etwas ohne deine Hände zu benutzen",
						"Iss etwas und tue so, als wäre es das leckerste, was du je gegessen hast",
						"Spiele 1 Runde lang den Gollum aus Herr der Ringe",
						"Spiele einen Wutanfall",
						"Der Spieler links von dir darf dir ein Gebräu aus allen möglichen Zutaten mischen und du musst es trinken",
						"Pose 1 Minute wie ein Bodybuilder",
						"Trage einen Turban aus Toilettenpapier",
						"Schnapp dir Schminkzeug und schminke die Person rechts neben dir",
						"Lass dich von anderen an einen Stuhl fesseln",
						"Ruf einen Kontakt aus Deinem Handy an und stöhne ins Telefon",
						"Imitiere eine Person deiner Wahl aus dieser Gruppe",
						"Mach einem Gegenstand eine Liebeserklärung",
						"Iss Katzen- oder Hundefutter",
						"Taste die Person rechts von dir ab",
						"Sag 3x hintereinander ganz schnell einen Zungenbrecher auf",
						"Ruf jemanden an und wünsche ihm ein frohes neues Jahr",
						"Bettle die Person dir gegenüber an, dir den Hintern zu versohlen",
						"Stelle innerhalb 1 Minute fest, wessen Haare am besten duften",
						"Hüpfe wie ein Frosch quakend durch den Raum",
						"Tanz zu dem Lied, was grade gespielt wird",
						"Schreibe mit einem Stift deinen Namen, benutze dabei jedoch deinen Fuß",
						"Versuche mit der Zungenspitze deine Nase zu berühren",
						"Iss einen Keks und pfeife nebenbei ein Lied"
						];