var ichhabnochniefragen = [
"... Ich habe noch nie gestohlen.",
"... Ich habe noch nie Drogen ausprobiert.",
"... Ich habe noch nie Handschellen getragen.",
"... Ich habe mich noch nie in ein Familienmitglied verliebt.",
"... Ich habe mich noch nie geprügelt.",
"... Ich habe noch nie jemanden wissentlich um Geld betrogen.",
"... Ich habe noch nie bei der Beichte gelogen.",
"... Ich habe noch nie Vandalismus betrieben.",
"... Ich habe mir noch nie gewünscht, mit jemanden den Körper tauschen zu können.",
"... Ich habe noch nie meine Eltern beklaut.",
"... Ich habe noch nie jemanden gemobbt.",
"... Ich habe noch nie die Zeche geprellt.",
"... Ich habe noch nie über jemanden Lügen verbreitet.",
"... Ich habe noch nie gekifft.",
"... Ich habe noch nie mit jemanden so gesprochen, dass er / sie geweint hat.",
"... Ich habe mir noch nie vor Angst in die Hose gemacht.",
"... Ich konnte noch nie Sex und Liebe trennen.",
"... Ich habe noch nie ein Fahrrad geklaut.",
"... Ich habe noch nie einen Gegenstand absichtlich kaputt gemacht, weil ich neidisch war.",
"... Ich habe noch nie im Zorn Gegenstände nach jemanden geworfen.",
"... Ich habe noch nie die Toilette des anderen Geschlechts benutzt.",
"... Ich habe noch nie jemanden gestalkt.",
"... Ich habe heute noch nie gefurzt.",
"... Ich war noch nie länger als 1 Jahr in eine Person verliebt, ohne mit ihr etwas zu haben.",
"... Ich war noch nie in eine Affäre verliebt.",
"... Ich habe noch nie einen Anwalt benötigt.",
"... Ich habe noch nie persönlich einen Drogendealer aufgesucht.",
"... Ich wollte noch nie eine platonische Freundschaft in eine „Freundschaft Plus“ verwandeln.",
"... Ich bin noch nie betrunken Auto gefahren.",
"... Ich habe noch nie so üblen Sex gehabt, dass ich danach Schluss gemacht habe.",
"... Ich habe noch nie gedacht, dass einer der Mitspieler einem Charakter aus einer Serie ähnelt.",
"... Ich wollte noch nie meine Familie bei Mitten im Leben anmelden.",
"... Ich habe noch nie ehrenamtlich für die Gesellschaft gearbeitet.",
"... Ich habe noch nie ein Geheimnis gehabt, das niemand außer mir jemals wissen darf.",
"... Ich habe noch nie gedacht, dass einer der Mitspieler heißer & attraktiver ist als mein momentaner Partner.",
"... Ich habe noch nie die Polizei geschmiert / bestochen.",
"... Ich habe noch nie einen Mitspieler gegoogelt.",
"... Ich habe mich noch nie absichtlich selbst verletzt.",
"... Ich bin noch nie bei einem Date ohne Unterwäsche aufgetaucht.",
"... Ich habe noch nie daran gedacht, jemanden richtig weh zu tun.",
"... Ich habe noch nie die Liebe meines Lebens getroffen.",
"... Ich habe noch nie Blut gespendet.",
"... Ich habe noch nie einen AIDS-Test gemacht.",
"... Ich habe noch nie Kummer in Alkohol ertränkt, bis ich nicht mehr gerade laufen konnte.",
"... Ich habe noch nie jemanden ins Auto gekotzt.",
"... Ich hatte noch nie eine Frisur, für die ich mich heute abgrundtief schäme.",
"... Ich habe noch nie länger als 3 Stunden mit einer Person telefoniert.",
"... Ich habe noch nie jemanden aus tiefsten Herzen gehasst.",
"... Ich hab noch nie im Auto Sex gehabt.",
"... Ich habe noch nie Penisbilder gegoogelt.",
"... Ich habe noch nie Angst vor Sex gehabt.",
"... Ich wurde noch nie von Eltern beim Sex erwischt.",
"... Ich habe noch nie mit einem Mitspieler hier Sex gehabt.",
"... Ich habe noch nie davon geträumt, meinem Partner beim Sex mit jemand anderem zuzuschauen.",
"... Ich hatte noch nie Schmerzen bei oder nach dem Sex.",
"... Ich habe noch nie den Bruder oder die Schwester meines Partners begehrt.",
"... Ich war noch nie schwanger / habe noch nie jemanden geschwängert.",
"... Ich habe noch nie einen Dreier gehabt.",
"... Ich habe noch nie auf eine/n platonische/n Freund/in masturbiert.",
"... Ich habe noch nie mit dem gleichen Geschlecht experimentiert.",
"... Ich habe noch nie einen One Night Stand gehabt.",
"... Ich habe mich noch nie mithilfe von Lebensmitteln selbst befriedigt.",
"... Ich habe noch nie Sex im Freien gehabt.",
"... Ich habe noch nie als heimlicher Voyeur jemanden beim Sex / beim Ausziehen / unter der Dusche beobachtet.",
"... Ich habe noch nie jemanden zu mir nachhause eingeladen, nur um Sex zu haben.",
"... Ich habe noch nie jemanden nach dem Sex oral zum Orgasmus gebracht.",
"... Ich habe noch nie mit jemand der vergeben war Sex gehabt.",
"... Ich habe noch mit jemanden, den ich im Internet kennen gelernt habe Sex gehabt.",
"... Ich habe mich noch nie nach dem Sex geschämt.",
"... Ich habe noch nie einen multiplen Orgasmus gehabt.",
"... Ich habe noch nie Sexspielzeug benutzt.",
"... Ich habe noch nie ein Date von jemanden von Tinder / Grindr etc. gehabt.",
"... Ich habe noch nie mit einem Date von Tinder / Grindr etc. geschlafen.",
"... Ich habe noch nie beim Anblick eines Penis gelacht.",
"... Ich habe noch nie mit meinem Partner einen Swinger Club besucht.",
"... Ich habe noch nie mehr als einen anderen Menschen am gleichen Tag befriedigt.",
"... Ich habe noch nie einen Pornofilm angeschaut.",
"... Ich habe noch nie auf eine MILF gestanden.",
"... Ich dachte noch nie morgens: „Bitte, lass uns nicht miteinander geschlafen haben!“",
"... Ich habe noch nie mit anderen gleichen Geschlechts zusammen masturbiert.",
"... Ich habe noch nie einen Footjob gegeben / bekommen.",
"... Ich habe noch nie eine Fickbeziehung gehabt.",
"... Ich habe noch nie beim Sex an meine/n Ex gedacht.",
"... Ich habe noch nie Gleitgel benutzt.",
"... Ich habe noch nie eine Sexpuppe in Händen gehalten.",
"... Ich habe mir noch nie gewünscht, einen der Anwesenden Personen hier oral zu befriedigen.",
"... Ich habe noch nie mit jemanden Sex gehabt der viel jünger / älter war.",
"... Ich habe noch nie mit mehr als 10 verschiedenen Menschen geschlafen.",
"... Ich habe noch nie eine Geschlechtskrankheit gehabt.",
"... Ich habe noch nie eine Beziehung gehabt, in der ich mit meinem Partner keinen Sex hatte.",
"... Ich habe noch nie einen Schwangerschaftstest gemacht.",
"... Ich habe noch nie einen Vaterschaftstest gemacht.",
"... Ich hatte noch nie an mehr als 5 verschiedenen Orten Sex. (als Ort zählt z.B. „im Bett“, d.h. verschiedene Betten zählen nicht als verschiedene Orte!)",
"... Ich habe noch nie mehr als 3 Orgasmen innerhalb von 24 Stunden gehabt.",
"... Ich habe mir noch nie beim Sex mit meinem Partner vorgestellt, er / sie wäre ein anderer den ich kenne.",
"... Ich habe noch nie einen Orgasmus bei einem Sextraum gehabt.",
"... Ich war noch nie in Versuchung meinen momentanen Partner zu betrügen.",
"... Ich habe noch nie einen Amateurporno gefilmt.",
"... einem Lehrer / einer Lehrerin auf den Arsch gestarrt.",
"... mit mir selbst geredet.",
"... meine Eltern beim Sex erwischt.",
"... in der Öffentlichkeit in die Hosen gemacht.",
"... in einen Busch gepinkelt.",
"... in der Dusche gesungen.",
"... über Sex geträumt.",
"... nackt im Freibad / See gebadet.",
"... meinen Namen gegoogelt.",
"... ein Tagebuch geführt.",
"... jemanden angekotzt.",
"... wegen einer Spinne gekreischt.",
"... Angst im Dunkeln gehabt.",
"... das ABC gerülpst.",
"... an einen elektrischen Zaun gefasst.",
"... während des Gehens gepinkelt",
"... auf einer Schulveranstaltung Drogen konsumiert",
"... Sex mit einer Person mit langen Haaren gehabt",
"... mit einem DJ geflirtet, nur so dass mein Musikwunsch erfüllt wird",
"... mit einer MILF rumgemacht",
"... ein benutztes Kondom gefunden",
"... einen Baum umarmt",
"... Sex mit jemandem gehabt ohne dass ich den vollständigen Namen der Person kannte",
"... einen Schwulen/ eine Lesbe geküsst",
"... mehr als einen Dildo/Vibrator besessen",
"... so viel getrunken, dass ich den Weg nach Hause nicht mehr gefunden habe.",
"... den Namen eines Anderen während dem Geschlechtsverkehr ausgesprochen.",
"... meinen Kopf kahl geschoren.",
"... Hilfsmittel bei der Selbstbefriedigung eingesetzt.",
"... jemanden geküsst und es danach bereut.",
"... den Wunsch gehabt, in eine andere Stadt zu ziehen.",
"... versucht, das Passwort eines Anderen zu erraten.",
"... erotische Fotos von mir schießen lassen.",
"... einen Strafzettel bekommen.",
"... etwas geklaut.",
"... auf der Arbeit im Lagerraum/Abstellraum rumgemacht.",
"... so ein gutes Verhältnis zu meinem Partner/Partnerin gehabt, dass ich die Badezimmertüre offen gelassen habe.",
"... jemandem das Leben gerettet.",
"... gekifft.",
"... härtere Drogen konsumiert.",
"... mein Flugzeug verpasst",
"... so heftig gelacht, dass ich pinkeln musste.",
"... meinen Eltern die Frage beantworten müssen, ob ich noch Jungfrau bin.",
"... beim Sex an eine andere Person gedacht.",
"... mit jemandem geschlafen an dessen Namen ich mich nicht erinnern konnte",
"... den Geburtstag eines Familienangehörigen vergessen",
"... jemanden entjungfert",
"... Fingernägel gekaut.",
"... in der Öffentlichkeit in die Hose gepinkelt.",
"... jemanden zufällig nackt gesehen den ich nicht nackt hätte sehen sollen",
"... im Vollrausch vergessen, wo ich wohne.",
"... eine Beziehung mit zwei Leuten gleichzeitig gehabt",
"... eine Beziehung mit zwei Leuten aus der selben Familie gehabt",
"... nach dem Feiern ein Blackout gehabt und erinnere mich teilweise an garnichts mehr.",
"... eine Verabredung angenommen nur um einen Freund/eine Freundin der Person kennen zu lernen",
"... meine Eltern beim Sex erwischt.",
"... eine Affäre mit einer verheirateten Person gehabt",
"... erotische Träume/Phantasien mit jemandem gehabt, den ich eigentlich nicht mag.",
"... mit insgesamt mehr als 15 Leuten in meinem Leben geschlafen",
"... so viel Angst bei einem Horrorfilm gehabt, dass ich laut geschrien habe.",
"... Sex in einem Aufzug gehabt",
"... in die Dusche gepinkelt",
"... einem anderen Autofahrer den Stinkefinger gezeigt",
"... Geld gefunden und es einfach behalten",
"... zu meinem Exfreund/Exfreundin gesagt: Lass uns Freunde bleiben.",
"... jemanden nach seiner Telefonnummer gefragt und danach nie angerufen",
"... jemandem die Füße geküsst",
"... einen Prominenten persönlich getroffen",
"... eine Schwarzfahrt in Kauf genommen, statt mir ein Ticket zu kaufen.",
"... eine Zigarre geraucht.",
"... schlafgewandelt.",
"... so viel getrunken dass ich am nächsten Tag um 13 Uhr immernoch betrunken war.",
"... einen Fallschirmsprung gemacht.",
"... vor 13 Uhr so viel getrunken dass ich sturz besoffen war.",
"... Sex im Bett meiner Eltern gehabt",
"... ein Auto gefahren mit dem ich nicht hätte fahren dürfen",
"... einem Freund/einer Freundin geraten, mit dem Partner/Partnerin Schluss zu machen.",
"... einen Partner betrogen (auch Küssen)",
"... den Notruf gewählt",
"... eine ganze Chilischote gegessen.",
"... einen Freund/eine Freundin meines Partners abgrundtief gehasst.",
"... Kondome mit Geschmack benutzt.",
"... etwas anderes als Klopapier benutzt",
"... einem Ex-Partner bei der Trennung unangebrachte Beleidigungen an den Kopf geworfen",
"... vor der Polizei fliehen müssen.",
"... außerhalb von meinem eigenen Zuhause nackt gebadet.",
"... einen Wettbewerb gewonnen",
"... mehr als eine Woche im Krankenhaus verbracht",
"... etwas das mit Sex zu tun hat im Internet gesucht",
"... Kängurufleisch gegessen.",
"... ein Kleidungsstück gekauft, getragen und am nächsten Tag zurück gebracht",
"... eine Zahnspange getragen",
"... einen besonderen Menschen verloren.",
"... in einem Kinofilm geschlafen",
"... meinen Chef angeschrien.",
"... das Herz eines Anderen gebrochen.",
"... die Schule geschwänzt.",
"... alleine zuhause so viel getrunken dass ich sturz betrunken war",
"... Strippoker gespielt.",
"... jemanden vom gleichen Geschlecht attraktiv gefunden.",
"... gesagt ich sei Single obwohl ich in einer Beziehung war",
"... einen Autounfall mit mehr als 200€ Schaden gehabt",
"... ein Kondom beim Überstreifen kaputt gemacht.",
"... drei Abende hintereinander einen Vollrausch",
"... einen Porno geschaut.",
"... heimlich meine Nachbarn beobachtet",
"... einen Porno gedreht.",
"... mein Alter verleugnet nur um jemanden näher kennen zu lernen",
"... wegen eines Katers die Schule / den Job geschwänzt",
"... zwei Personen gleichzeitig gedated weil ich mich nicht entscheiden konnte",
"... im Beisein meines Partners geweint",
"... mit einem fremden Auto einen Unfall gebaut",
"... mit jemandem geschlafen den ich nicht kannte",
"... ein Auge auf die Eltern eines Freundes geworfen.",
"... den Wunsch gehabt, unsichtbar zu sein.",
"... Sex gehabt während andere Personen im Raum waren",
"... in einem Raum geschlafen in dem andere Leute Sex hatten",
"... meine Eltern gefragt wo ich genau gezeugt wurde",
"... draußen im Gras geschlafen, weil ich so betrunken war.",
"... eine erotische SMS / eMail / Nachricht versendet",
"... auf eine andere Person gekotzt.",
"... das Geheimnis eines anderen ausgeplaudert (versehentlich oder absichtlich)",
"... den Wunsch gehabt, ein Mann/eine Frau zu sein.",
"... einen Korb erhalten wenn ich mit jemandem ausgehen wollte",
"... eine Schlägerei mit einem Türsteher gehabt",
"... einen Rausschmiss in einem Club bekommen",
"... als Jugendlicher vor einem Geschäft gewartet, bis ein Erwachsener kommt, um mir Alkohol zu kaufen.",
"... den Wunsch gehabt, älter zu sein.",
"... Eifersucht verspürt als ich hörte dass ein Prominenter für den ich schwärme vergeben ist",
"... Sex mit einem Arbeitskollegen gehabt.",
"... ein Fahrrad gestohlen",
"... nach einem Besuch beim Friseur geweint",
"... das Erlebnis gehabt, von der Polizei durchsucht werden zu müssen.",
"... große Schadenfreude verspürt als ich hörte dass einem anderen etwas sehr schlimmes zugestoßen ist",
"... in einem Wutanfall etwas zerstört",
"... mich selbst in den Schlaf geweint.",
"... einen Partner gehabt dessen Eltern mich nicht leiden konnten",
"... einen Partner gehabt dessen Eltern ich nicht leiden konnte",
"... eine Waffe abgefeuert.",
"... ein anderes Fahrzeug beschädigt und bin dann einfach weiter gefahren",
"... darüber nachgedacht, was nach dem Tod passieren wird.",
"... Sex gehabt ohne vorher die Schuhe auszuziehen",
"... Sex auf dem Küchentisch gehabt",
"... beim Sex den Großteil meiner Klamotten angelassen",
"... das Haus verlassen ohne Unterwäsche drunter zu ziehen",
"... solche Aggressionen gehabt, dass ich jemanden hätte töten können.",
"... Sex an einem sehr ungewöhnlichen Ort gehabt",
"... jemanden gedated, der eigenartig war.",
"... vorgegeben ich sein homosexuell um in Ruhe gelassen zu werden",
"... so viel Angst gehabt dass ich am ganzen Körper gezittert habe",
"... während eines Dates eine Ausrede benutzt, um das Treffen frühzeitig zu beenden.",
"... ein Telefonat von mehr als 5 Stunden geführt",
"... das Gefühl gehabt, egoistisch zu sein.",
"... einen Abend ohne Freunde oder Bekannte in einem Club verbracht",
"... eine Schlange in meinen Händen gehalten.",
"... so getan als wäre ich betrunken",
"... ein Strip-Lokal von innen gesehen",
"... in einem Sexshop eingekauft",
"... etwas im Internet bestellt weil ich mich nicht getraut habe es im Laden zu kaufen",
"... meinen Freund/meine Freundin betrogen.",
"... versucht etwas zu kaufen für das ich mich geschämt habe und bin daher unauffällig durch die Regale geschlendert um nicht aufzufallen",
"... für jemanden gestripped",
"... jemanden für mich strippen lassen",
"... ein sehr peinliches Rollenspiel mitgemacht",
"... überlegt, mir ein Tattoo stechen zu lassen.",
"... so viel getrunken dass ich beim Sex eingeschlafen bin",
"... eine Frage bei einem Trinkspiel falsch beantwortet",
"... ein Referat aus dem Internet ausgedruckt und in der Schule/Uni vorgetragen.",
"... falsche Angaben gemacht bei der Frage mit wie vielen Leuten ich geschlafen habe.",
"... ein Wort gegoogelt, weil ich nicht wusste, wie man es schreibt.",
"... ein übles Gerücht über jemanden in die Welt gesetzt",
"... Pornofilme bei mir zuhause versteckt",
"... versucht Bilder/Videos auf dem Computer zu verstecken",
"... Pornohefte gekauft",
"... Pornoheft bei mir zuhause versteckt",
"... einen Tag ohne Unterwäsche verbracht",
"... einen Tag im Pyjama verbracht",
"... einen Neujahrsvorsatz tatsächlich eingehalten",
"... einen ganzen Arbeitstag im Internet verbracht",
"... einen ganzen Tag Computer gespielt",
"... 24 Stunden am Stück Fernsehen geschaut",
"... einen Film mehr als 15 mal gesehen",
"... eine Fotokopie von meinem Gesicht gemacht",
"... eine Fotokopie von meinem Hintern gemacht",
"... ein Angebot für einen Dreier bekommen",
"... bei einem Dreier mitgemacht",
"... ein perverses Bild über Snapchat verschickt",
"... ein Bild verschickt für das ich mich im Nachhinein schäme",
"... betrunken Nachrichten gesendet die ich nüchtern bereuet habe",
"... vor einem Flug getrunken um meine Nerven zu beruhigen",
"... von meinen Eltern Geld geklaut",
"... einen Fan-Brief an einen Promi geschrieben",
"... während dem Sex anfangen müssen zu lachen",
"... die Unterwäsche meines Partners ausgeliehen",
"... über einen Freund gedacht dass seine Eltern bei der Erziehung versagt haben",
"... ein Möbelstück beim Sex kaputt gemacht",
"... Sex in allen Räumen meiner Wohnung gehabt",
"... ein Date mit dem Ex einer Freundin/eines Freundes gehabt",
"... hinter dem Kühlschrank sauber gemacht",
"... ein Date mit jemandem gehabt den ich über das Internet kennen gelernt habe",
"... drei Nächte am Stück durchgefeiert",
"... vor dem Spiegel getanzt",
"... vor einem Spiegel gesungen",
"... so getan als würde ich vor einem Millionenpublikum stehen und singe (o.Ä.)",
"... Tierfutter probiert",
"... als Notfall in einem Krankenwagen gelegen",
"... Sex in einem Auto, Zug oder Bus gehabt",
"... einen Dildo in meinen Händen gehalten",
"... online über Sexspielzeug recherchiert",
"... eine Party erst am späten Morgen des Folgetags verlassen",
"... so dringend aufs Klo gemusst dass ich es nicht geschafft habe",
"... etwas besessen dass ich immer versteckt habe wenn Freunde kamen",
"... eine eMail Adresse angelegt die ich nutze wenn ich anonym bleiben will",
"... meine Eltern/Geschwister nackt gesehen",
"... ein Tier umgebracht",
"... jemanden auf der Straße gesehen und so getan als hätte ich ihn nicht gesehen",
"... die Minibar eines Hotels geleert",
"... versucht an das Passwort einer anderen Person zu kommen",
"... eine Kneipenschlägerei gehabt",
"... mit jemandem aus einem anderen Land geschlafen",
"... während eines Wutanfalls etwas zerstört",
"... über meine/n Ex gedacht: Wie konnte ich nur mit ihm/ihr zusammen sein?",
"... einen Ladendiebstahl beobachtet",
"... mit einer Person geflirtet obwohl ich wusste dass die Person vergeben ist",
"... einen Auftritt im Fernsehen gehabt",
"... romantische Gefühle für den Partner eines Familienmitglieds gehabt",
"... bei Bekannten in den Badezimmerschrank geschaut",
"... einen Arzttermin vergessen",
"... Kondome gekauft",
"... einen Haarschnitt gehabt für den ich mich heute noch schäme",
"... Essensreste in meinem Bett gefunden",
"... eine Straftat begangen",
"... ein und dieselbe Unterwäsche länger als 5 Tage getragen",
"... eine Kündigung erhalten",
"... jemanden gleichzeitig geliebt und gehasst",
"... besoffen ein Geheimnis ausgeplaudert",
"... eine Hochzeitsrede gehalten",
"... meine Eltern oder Nachbarn beim Sex gehört",
"... während des Sex an eine andere Person gedacht",
"... während des Sex gähnen müssen",
"... in einer Alltagssituation gemerkt dass ich erregt bin und mich dafür geschämt",
"... während dem Sex mit Lebensmitteln experimentiert",
"... während dem Sex mit Haushaltsgegenständen experimentiert",
"... so viel getrunken dass ich bei einer Party rausgeworfen wurde",
"... mehr als 2 Wochen am Stück keinen Alkohol angerührt (letzten 2 Jahre)",
"... mit jemandem geschlafen den ich verleugnen würde",
"... ein erotisches Geschenk für meinen Partner gemacht",
"... mit jemandem über meine sexuellen Phantasien gesprochen",
"... heimlich meinen Ex gestalked",
"... gewünscht die Eltern eines Freundes wären meine",
"... so viel getrunken dass ich den ganzen nächsten Tag im Bett verbringen musste",
"... Sex im Auto gehabt.",
"... mehr als 100€ fürs Taxi ausgegeben",
"... vergessen dass Feiertag/Wochenende war und bin zur Arbeit/Schule erschienen",
"... eine durch Geschlechtsverkehr übertragbare Krankheit gehabt.",
"... eine Panne gehabt, weil ich vergessen habe zu tanken",
"... so viel getrunken dass ich nur mit fremder Hilfe nach Hause gekommen bin",
"... mehrere Stunden am Stück ohne Kleidung verbracht",
"... Sex mit mehr als einer Person gleichzeitig gehabt.",
"... völlig nackt geschlafen",
"... etwas aus einem Hotelzimmer mitgehen lassen",
"... an meiner Unterwäsche gerochen nur um zu sehen ob sie noch frisch ist",
"... Peitschen und Ähnliches beim Sex benutzt.",
"... mit einer deutlich älteren Person geschlafen ",
"... mit einer deutlich jüngeren Person geschlafen",
"... eine vertrauliche SMS/eMail an den falschen Empfänger gesendet",
"... jemanden kennen gelernt der schonmal im Gefängnis saß",
"... meinen eigenen Namen gegoogelt",
"... heimlich das Getränk eines anderen ausgetrunken",
"... auf einer Hochzeit gedacht, dass diese Ehe nicht lange halten wird",
"... einen Liebesbrief geschrieben",
"... ein Liebesgedicht geschrieben",
"... bei einem Buch die letzte Zeile zuerst gelesen",
"... jemanden geküsst, ohne seinen Namen zu wissen.",
"... Sexspielzeug gekauft",
"... mit jemandem geschlafen um mich an jemand anderem zu rächen",
"... mit jemandem aus meinem Büro geschlafen",
"... etwas gegessen obwohl ich wusste dass das Haltbarkeitsdatum abgelaufen ist",
"... meinen Partner mit dem Namen meiner/meines Ex angesprochen",
"... gleichgeschlechtliche Gefühle gehabt",
"... mehr als 3 Monate ohne Sex verbracht (letzten 2 Jahre)",
"... mit jemandem geschlafen der auch mit meinem besten Freund/meiner besten Freunden geschlafen hat",
"... mehr als 200€ an einem Abend ausgegeben",
"... in der Öffentlichkeit gekotzt",
"... Handschellen am Armgelenk getragen",
"... Ich liebe dich gesagt obwohl ich es nicht so meinte",
"... etwas geschluckt was ich nie wieder freiwillig schlucken würde",
"... an den Ohrläppchen meines Partners geleckt",
"... Massageöl benutzt",
"... ein Date gehabt nur um einer anderen Person weh zu tun",
"... das Disneyland besucht.",
"... das Etikett eines Kleidungsstücks entfernt weil es eine Billigmarke war",
"... etwas auf der Arbeit geklaut",
"... Silikonbrüste berührt",
"... beim Aufwachen gedacht: Wo bitte bin ich denn hier?",
"... während des Sex gefurzt",
"... vor einer Menschenmenge Karaoke gesungen.",
"... mein erstes Date im Kino verbracht",
"... einen handfesten Streit in der Öffentlichkeit gehabt",
"... einen Bungee-Sprung gemacht",
"... gesagt die Verbindung sei schlecht nur um ein Telefonat zu beendet",
"... so getan als hätte ich eine Nachricht nicht gelesen weil ich nicht darauf antworten wollte",
"... nach einem Besuch beim Friseur geweint ",
"... eine Sex-Beziehung zu einer Person gehabt mit der ich nicht zusammen war",
"... mit jemandem geschlafen den ich eine Stunde zuvor noch nicht kannte",
"... darüber nachgedacht sexuelle Rollenspiele zu machen",
"... mit jemandem geschlafen den ich über das Internet kennen gelernt habe",
"... etwas im Wert von über 500€ kaputt gemacht oder verlegt",
"... in öffentlichen Verkehrsmitteln absichtlich den Platz gewechselt um neben einer attraktiven Person zu sitzen",
"... Sex in der Öffentlichkeit gehabt (z.B. öffentliche Toilette)",
"... Sex in einer Badewanne gehabt",
"... bei einem Date bezüglich meiner Alters oder meiner Herkunft gelogen",
"... jemandem gesagt dass ich seinen Körper schön finde",
"... ein Kompliment über meine Geschlechtsteile bekommen",
"... so getan als wäre ich krank nur um nicht mit jemandem schlafen zu müssen",
"... ein Angebot für Sex abgelehnt",
"... jemanden in einer zweideutigen Situation erwischt was mir im Nachhinein immernoch peinlich ist",
"... meinen Partner mit dem Namen eines Ex-Partners angesprochen",
"... einen Orgasmus vorgetäuscht",
"... nach dem Sex Biss- oder Kratzspuren gehabt",
"... mit meinem Partner über alle meine sexuellen Wünsche gesprochen",
"... ein Tier auf den Mund geküsst",
"... jemanden beim Masturbieren beobachtet",
"... beim Masturbieren jemanden zuschauen lassen",
"... einen Freund verteidigt auch wenn ich wusste dass er im Unrecht ist",
"... für meinen besten Freund/meine beste Freundin gelogen",
"... bei einem Doppel-Date mitgemacht nur damit ein Freund/eine Freundin mit ihrem Schwarm ausgehen kann",
"... beim Speed-Dating mitgemacht",
"... in einem Hotelzimmer den Pornokanal geschaut",
"... so laut gestöhnt dass ich Angst hatte jemand anderes könnte es gehört haben",
"... jemanden mit sehr unangenehmen Mundgeruch geküsst",
"... jemanden beim Sex beobachtet",
"... jemandem etwas ekliges in den Briefkasten gesteckt ",
"... einen Brief eingeworfen und versucht ihn wieder zu bekommen",
"... Flaschendrehen mit zweideutigen Aufgaben gespielt",
"... Sex im Freien gehabt",
"... einen Swingerclub von innen gesehen",
"... im Auto ganz laut die Musik aufgedreht und mitgesungen",
"... mit anderen Personen zusammen einen Porno gesehen",
"... einen Liebesbrief erhalten",
"... ein One-Night-Stand gehabt",
"... etwas beim Sex getan wobei ich mich total blamiert habe",
"... mit jemandem geschlafen obwohl ich eigentlich keine Lust dazu hatte",
"... Sex während der Periode gehabt",
"... auf einer Party mit jemandem rumgemacht",
"... beim Sex Alltagsprobleme diskutiert",
"... in öffentlichen Verkehrsmitteln mit jemandem (z.B. meinem Partner) rumgeknutscht",
"... das Jugendamt alarmiert",
"... körperliches Unwohlsein vorgetäuscht",
"... meine Hausaufgaben abgeschrieben",
"... bei einer Klausur abgeschrieben",
"... eine Klausur geschrieben auf die ich weniger als eine Stunde gelernt hatte",
"... an einem Casting teilgenommen",
"... jemanden heimlich beobachtet",
"... mit jemandem geschlafen der jünger als 16 Jahre alt war",
"... ein Verkehrsschild überfahren",
"... eine rote Ampel überfahren",
"... Strapse oder Lack und Leder getragen",
"... mehr als 10 verschiedene Stellungen ausprobiert",
"... bei einem einzigen Mal Sex mehr als 5 verschiedene Positionen ausprobiert.",
"... mit mehr als einer Person gleichzeitig eine sexuelle Beziehung",
"... mit jemandem geknutscht dessen Vornamen ich nicht kannte",
"... einen Partner der deutlich unter meinem Niveau war",
"... mit meinen Eltern über Verhütung gesprochen",
"... Oralsex während dem Autofahren gehabt",
"... 2 Wochen ohne einen einzigen Orgasmus verbracht (letzten 2 Jahre)",
"... reizvolle Unterwäsche getragen",
"... versucht mit einem falschen Geldschein zu bezahlen",
"... das Handy meines Partner durchstöbert",
"... die eMails / Nachrichten meines Partners durchsucht",
"... Sex mit einem Vorgesetzen/Lehrer/...",
"... um Sex gebettelt",
"... versucht den G-Punkt zu finden",
"... einem Partner zuliebe etwas unangenehmes, ekliges oder perverses ausprobiert",
"... eine Kontaktanzeige aufgegeben oder auf eine geantwortet",
"... einen erotischen Traum gehabt den ich niemals in die Tat umsetzen würde",
"... beim Aufwachen gedacht: Wer ist das neben mir?",
"... bei einer Sex-Hotline angerufen",
"... Sexspielzeug von anderen Leuten gefunden",
"... etwas gekauft was ich meinem Partner verschwiegen habe weil ich wusste dass er das nicht unterstützt",
"... so getan als hätte ich kein Geld mehr weil ich für eine bestimmte Sache kein Geld ausgeben wollte",
"... mit einem Ex-Partner geschlafen",
"... versaute Sachen gesagt um jemanden scharf zu machen",
"... etwas auf jemand anderen geschoben nur um nicht zugeben zu müssen dass ich es gewesen bin",
"... wegen eines Sexunfalls ins Krankenhaus gemusst",
"... ein ganz besonders außergewöhnliches Sexerlebnis gehabt",
"... beim Sex meinem Partner die Dominanz überlassen",
"... erotische Bilder oder Kalender aufgehängt",
"... jemanden per Oralsex zum Orgasmus gebracht",
"... Sex in einem Fahrstuhl",
"... ein Geschenk vergessen",
"... Bilder meines Ex-Partners ins Internet gestellt",
"... einer religiösen Sekte angehört",
"... etwas eingenommen um mich sexuell zu stimulieren",
"... mit jemandem geschlafen ohne zu verhüten.",
"... hunderte Kilometer zurück gelegt nur um einen bestimmten Menschen zu sehen",
"... eine Mutprobe mitgemacht",
"... einen Partner gehabt der deutlich mehr Sex wollte als ich",
"... deutlich mehr Sex gehabt als im Moment",
"... etwas deutlich über seinem Wert verkauft",
"... etwas unanständiges im Kino getan",
"... etwas besonders ekliges gegessen.",
"... davon geträumt eine k?rperliche Beziehung mit einem völlig Fremden zu haben.",
"... mit anst??igen Gefälligkeiten für etwas bezahlt.",
"... jemandem unverbindlichen Sex angeboten.",
"... einen Partner gehabt für den ich mich geschämt habe.",
"... künstliches Gleitmittel benutzt.",
"... Sex in einem öffentlichen Schwimmbad / am Strand gehabt.",
"... meinen bzw. den Penis meines Partner mit dem Lineal vermessen.",
"... jemandem wildfremden auf der Straße geholfen.",
"... einen ganzen Tag ohne Kleidung verbracht.",
"... einem Partner versaute Kosenamen gegeben.",
"... mehr als einmal Sex unmittelbar hintereinander gehabt.",
"... nach dem Sex masturbiert weil ich nicht befriedigt war.",
"... Fantasien gehabt, für die ich mich schäme.",
"... Fantasien gehabt in denen ich gefoltert oder gefesselt wurde.",
"... Fesselspielchen gemacht.",
"... einen Sex-Ratgeber gelesen.",
"... eine Bravo aufgeschlagen nur um den Dr. Sommer Teil zu lesen.",
"... einem Partner von Sexerlebnissen mit meinem Ex erzählt.",
"... Sex an einem anderen Ort als im Bett gehabt.",
"... Sex mit einer Person gehabt mit der ich nicht zusammen war.",
"... an einer Wand gelauscht um andere beim Sex zu hören.",
"... jemanden an den Füßen stimuliert.",
"... mit dem Schluss machen gewartet weil ich noch niemand Neues hatte.",
"... meinen eigenen Intimbereich fotografiert.",
"... meinem Intimbereich einen Kosenamen gegeben/geben lassen.",
"... ein Partyspiel gespielt bei dem es auch ums ausziehen ging.",
"... Sex in einer Umkleidekabine gehabt.",
"... einen Liebesakt gehabt der länger als eine Stunde gedauert hat.",
"... wilden Sex (Quickie ohne Vorspiel) gehabt.",
"... telefoniert / gechattet während ich auf dem Klo saß.",
"... von Sex mit einem Dienstleister (Klempner, Krankenschwester,...) geträumt.",
"... den Multiplayer ausprobiert.",
"... an einem FKK Strand gebadet.",
"... die Anfrage eines Vorgesetzten auf Facebook ignoriert.",
"... per SMS mit jemandem Schluss gemacht.",
"... etwas zerstört nur um mich an jemandem zu rächen.",
"... eine erotische Massage gegeben oder erhalten.",
"... wo anders als zuhause masturbiert.",
"... Rosen geschenkt bekommen.",
"... in den Spiegel geschaut und gedacht: Wow. Sexy!",
"... eine Spam-eMail angeklickt weil ich dachte, dass sie echt ist.",
"... eine Fernbeziehung gehabt.",
"... eine Beziehung mit einer Person gehabt die ich über das Internet kennen gelernt habe.",
"... bei einer Dating-Website ein Profil erstellt.",
"... unter einer falschen Identität versucht einen Bekannten/Freund über das Internet zu kontaktieren.",
"... hinter seinem Rücken schlecht über meinen Partner gesprochen.",
"... heimlich unter dem Tisch Händchen gehalten.",
"... gewünscht ich könnte einfach wieder ein kleines Kind sein.",
"... mehr als eine halbe Stunde im Internet nach einer bestimmten Person (nicht ich selbst) recherchiert.",
"... erst im Zug bemerkt dass ich gar kein Ticket gekauft hatte.",
"... einen Schwangerschaftstest gekauft.",
"... einen ganzen Tag im Bett verbracht obwohl ich nicht krank war.",
"... nachts im Gras gelegen und Sternschnuppen beobachtet.",
"... das Kamasutra gelesen.",
"... Sex im Hotel gehabt.",
"... eine falsche Identität im Internet benutzt.",
"... darüber nachgedacht wie es wohl wäre das andere Geschlecht zu haben.",
"... ein romantisches Gedicht für meinen Partner vorgetragen.",
"... in der Sauna andere Leute beobachtet.",
"... mich selbst gestreichelt und mir vorgestellt es sei jemand anderes.",
"... überlegt ein Bordell zu besuchen.",
"... eine Beziehung gehabt obwohl ich immer im Hinterkopf hatte: heiraten werde ich ihn/sie auf keinen Fall!",
"... etwas besser gekonnt als alle meine Freunde.",
"... erotische Unterw?sche getragen.",
"... nackt ein Auto gefahren.",
"... für eine deutlich jüngere Person geschwärmt.",
"... für eine deutlich ältere Person geschwärmt.",
"... einen Lehrer/Vorgesetzten nackt vorgestellt.",
"... nackt vor dem Computer gesessen.",
"... ausgenutzt dass jemand total betrunken war.",
"... im Internet nach Nacktfotos eines Prominenten gesucht.",
"... eine Stellung aus dem Kamasutra ausprobiert.",
"... mit jemandem geschlafen den ich eigentlich nicht attraktiv fand.",
"... meine Unterwäsche irgendwo verloren oder vergessen.",
"... Telefonsex gehabt.",
"... ein Onlinespiel gespielt.",
"... einen Knutschfleck gehabt.",
"... mit jemandem über intime Details meines Sexlebens gesprochen (nicht meinem Freund/meiner Freundin).",
"... einen Partner gehabt der mich nicht ausreichend sexuell befriedigt hat.",
"... gemeinsam mit einer anderen Person geduscht oder gebadet.",
"... sexuelle Wünsche / Fantasien gehabt die ich mich nicht getraut habe mit meinem Partner zu besprechen.",
"... eine Beziehung zu einer Person gehabt die maßgeblich auf Sex basiert hat.",
"... mit jemandem geschlafen während ich ziemlich betrunken war.",
"... mit jemandem geschlafen mit dem ich im Nachhinein lieber nicht geschlafen hätte.",
"... nach dem Sex das Gefühl gehabt nicht richtig befriedigt zu sein",
"... meinen Partner mit der Hand stimuliert.",
"... Sexspielzeug besessen.",
"... Selbstgespräche geführt.",
"... unter der Dusche gesungen.",
"... nackt in einem See / Meer gebadet.",
"... mit einem Kuscheltier geredet.",
"... länger als 3 Tage nicht geduscht.",
"... im Stehen gepinkelt.",
"... den Namen eines Ex-Partners vergessen.",
"... eine Beziehung mit einer Person mit der ich früher mal zusammen war geleugnet.",
"... eine Person in der Öffentlichkeit angesprochen einfach weil ich sie attraktiv fand.",
"... essbare Unterwäsche benutzt.",
"... einen Partner gehabt für den ich Dinge ausprobiert habe die ich eigentlich nie machen wollte.",
"... überlegt in ein SM- / Bondage Studio zu gehen.",
"... noch beim ersten Date mit jemandem geschlafen.",
"... Sex gehabt ohne zu verhüten.",
"... beim Oralsex verhütet (wegen Geschlechtskrankheiten).",
"... davon geträumt einen Klassenkameraden / Kommilitonen / Kollegen nackt zu sehen.",
"... andere Leute (Freunde, Kollegen, Bekannte) beim Sex vorgestellt.",
"... Eifersucht verspürt, weil andere ein spannenderes Liebesleben haben als ich.",
"... über die Vergrößerung meiner Geschlechtsorgane nachgedacht.",
"... einen Partner gehabt, der in Sachen Sex nicht so offen war wie ich.",
"... einen Partner gehabt, der in Sachen Sex deutlich offener war als ich.",
"... über einen Partnertausch nachgedacht.",
"... beim Sex die Dominanz übernommen.",
"... jemandem ein Kompliment über seine Geschlechtsteile gemacht.",
"... Fotos / Videos während dem Sex gemacht.",
"... gesagt bekommen ich sei gut im Bett.",
"... im Schwimmbad unter Wasser gefummelt.",
"... eine Stellung im Stehen ausprobiert.",
"... Hilfsmittel beim Sex eingesetzt (Penisringe, Vibratoren,...).",
"... nackt oder zumindest halbnackt vor eine Webcam gesessen.",
"... für erotisches Material bezahlt (Live-Cams, Pornohefte, Videos, etc).",
"... für erotische Dienstleistungen bezahlt.",
"... nach Nacktfotos einer bestimmten Person im Internet gesucht.",
"... davon geträumt an einem außergewöhnlichen Ort Sex zu haben.",
"... von einem Partner ein erotisches Geschenk erhalten.",
"... versucht anstößige Geheimnisse über einen Freund herauszubekommen.",
"... fantasiert, wie bestimmte Leute wohl beim Sex aussehen.",
"... beim Sex oder der Masturbation gestöhnt.",
"... davon geträumt beherrscht oder dominiert zu werden.",
"... gedacht: Wenn er/sie mich jetzt anspricht würde ich noch auf einen Kaffee mit rein kommen",
"... darauf gewartet dass mich jemand anspricht, weil ich mich selbst nicht getraut habe.",
"... eine Beziehung gehabt die ich im Nachhinein bereue.",
"... eine Person geküsst die das gleiche Geschlecht hat wie ich.",
"... einen Partner gehabt bei dem ich Angst hatte ihn meinem Eltern vorzustellen.",
"... Verhütungsmittel mitgeführt: Nur für den Fall.",
"... den Sex ausfallen lassen weil keine Verhütungsmittel zur Hand waren.",
"... einen romantischen Abend mit Kerzen, Rosen usw verbracht.",
"... eine Badeessenz für romantische Abende zu zweit benutzt.",
"... nach dem Aufwachen gedacht: Was ist gestern Abend eigentlich noch passiert?",
"... mehrere Orgasmen relativ unmittelbar nacheinander gehabt.",
"... meinem Partner Frühstück ans Bett gebracht.",
"... ein Buch gelesen das mich richtig angeturnt hat (z.B. Fifty Shades of Grey).",
"... eine Party besucht mit der Absicht heute bloß nicht alleine nach Hause zu gehen.",
"... das Gefühl gehabt mit meinem Körper komplett zufrieden zu sein.",
"... Lust gehabt, mit einem der anwesenden Spielern zu schlafen.",
"... auf einer Party Sex gehabt.",
"... einen ganzen Tag lang geweint.",
"... mich selbst berührt.",
"... einen H?hepunkt gehabt.",
"... die Klamotten von jemand anderem versteckt.",
"... einen guten Freund /eine gute Freunden gehabt mit dem/der ich über intime Angelegenheiten gesprochen habe.",
"... Natursekt-Spielchen (Urin) ausprobiert.",
"... gemeinsam mit einem Partner geduscht oder gebadet.",
"... für Sex bezahlt.",
"... einen Spiegel benutzt, um meine Intimzonen genauer zu betrachten.",
"... Sex gehabt bei dem ich mich über einen Spiegel im Raum selbst beobachten konnte.",
"... Sex gehabt bei dem ich nicht zum Orgasmus gekommen bin.",
"... mit meinem Partner zusammen erotische Filme oder Bilder angeschaut.",
"... Nacktbilder von mir über das Internet verschickt.",
"... das Gefühl gehabt dem biologisch benachteiligtem Geschlecht anzugehören.",
"... intime Details über einen meiner Ex-Partner ausgeplaudert.",
"... jemandem einfach so auf den Hintern gehauen (nicht mein Freund/meine Freundin).",
"... jemanden über eine Datingseite im Internet kennen gelernt.",
"... Cybersex ausprobiert.",
"... wegen Sex Muskelkater gehabt.",
"... jemanden beim Pornos schauen erwischt.",
"... Pornos geschaut und jemand kam rein.",
"... mit zwei Leuten am selben Tag geschlafen.",
"... einen Geschlechtsakt gehabt, der länger als drei Stunden gedauert hat.",
"... das Gefühl gehabt mich einem Partner voll und ganz hingeben zu wollen.",
"... spontanen Sex gehabt, obwohl ich bereits spät dran war.",
"... mit jemandem geflirtet mit dem ich keine Beziehung, sondern bloß Sex wollte.",
"... mehr als drei Orgasmen an einem Tag gehabt.",
"... überlegt ob ein Freund/eine Freundin wohl mit mir schlafen wollen würde.",
"... halb nackt die Türe für jemanden geöffnet (z.B. Postbote).",
"... in den persönlichen Dateien auf einem fremden Computer gestöbert.",
"... jemanden einen geblasen.",
"... aus einem Teller Wein getrunken.",
"... Sex auf einem Baum gehabt.",
"... in einer Vorlesung/Unterrichtsstunde geschlafen.",
"... einen Penis in der Hand gehalten.",
"... auf jemanden uriniert.",
"... ein Mädchen geküsst.",
"... etwas mit einer Person angefangen, die zu diesem Zeitpunkt in einer Beziehung war.",
"... so viel getrunken, dass ich mich ?bergeben musste.",
"... eine Eifersuchtsszene geschoben.",
"... eine Frau oral befriedigt (lecken).",
"... bei Wahrheit oder Pflicht eine peinliche Pflicht ausführen müssen.",
"... eine Sucht nach etwas entwickelt.",
"... peinliche Rechtschreibfehler gemacht.",
"... einen erfolgreichen Versuch unternommen, abzunehmen.",
"... eine so massive Wut entwickelt, dass ich jemanden lauthals anschreien musste.",
"... mit einer elektrischen Zahnbürste onaniert.",
"... etwas verloren weil ich so betrunken war.",
"... einen Knochenbruch gehabt.",
"... so viel getrunken das ich mich an einiges nichtmehr erinnern kann.",
"... vor lachen geweint.",
"... Herzschmerz gehabt.",
"... etwas nur aus Höflichkeit gegessen, obwohl es in Wahrheit nicht schmeckte.",
"... bei diesem Spiel etwas neues über einen Mitspieler erfahren, was ich nicht von ihm/ihr erwartet hatte.",
"... mit dem besten Freund/ der besten Freundin meines Ex Partners was gehabt.",
"... ein Konzert besucht.",
"... einen wichtigen Termin verschlafen.",
"... ein Buch für die Schule komplett durchgelesen.",
"... darüber nachgedacht eine Beziehung zu beenden.",
"... ein Möbelstück selbst aufgebaut.",
"... bei einem Film geweint.",
"... jemandem im Urlaub kennengelernt und weiterhin Kontakt gehalten.",
"... versucht jemandem den Partner auszuspannen.",
"... mein Handy in die Toilette fallen lassen.",
"... meine Führerscheinprüfung (Theorie und/oder Praxis) wiederholen müssen.",
"... zum Idiotentest (Führerschein) gehen müssen.",
"... etwas wertvolles kaputt gemacht.",
"... vergessen meine Pille zu nehmen.",
"... mit meinem Haustier gekuschelt.",
"... mich so sehr blamiert das ich mich bis heute dafür schäme.",
"... eine Entscheidung getroffen, die ich schon unmittelbar danach bereut habe.",
"... gehofft bei dem Spiel nicht als einziger trinken zu müssen.",
"... mich selbst für etwas belohnt.",
"... eine Brille getragen.",
"... bezüglich meines Gewichts um bis zu 20kg gelogen.",
"... meine Eltern belogen!",
"... ein Versprechen gebrochen.",
"... eine wichtige Prüfung nicht bestanden.",
"... ein Haustier gehabt.",
"... meinen Partner ausgezogen.",
"... mit jemandem zusammen geduscht.",
"... bei diesem Spiel als einziger nicht getrunken.",
"... bei diesem Spiel als einziger trinken m?ssen.",
"... gegen das andere Geschlecht bei einem Trinkspiel gewonnen.",
"... Sperma geschluckt.",
"... Analsex gehabt.",
"... im Wald einen geblasen bekommen.",
"... in der Uni / Schule Sex gehabt.",
"... Lebensmittel beim Sex benutzt.",
"... Popel gegessen.",
"... mit einer fremden Zahnbürste meine Zähne gebürstet.",
"... aus Versehen im Kino aus dem falschen Glas getrunken oder vom falschen Popkorn gegessen.",
"... meine(n) Ex in der Stadt verfolgt.",
"... einen Erotik Roman gelesen.",
"... im Schlaf gesabbert.",
"... im Schlaf geredet.",
"... Sex im Freien gehabt und bin dabei erwischt worden.",
"... String-Tangas getragen.",
"... eine Person geküsst, die hier im Raum ist.",
"... so getan als würde ich schlafen nur um nicht mit der Person schlafen zu müssen.",
"... so getan die Pille nicht genommen zu haben um dem Sex zu entgehen.",
"... mich alleine betrunken.",
"... auf der Arbeit Alkohol getrunken.",
"... mir einen meiner jetzigen Mitspieler nackt vorgestellt.",
"... Sex gehabt und ein Freund kam in den Raum.",
"... was mit einem Austausschüler / einer Austausschülerin gehabt.",
"... mit jemandem geschlafen, den ich im Urlaub kennengelernt habe.",
"... vegan gelebt.",
"... erlebt, dass mich ein Freund meines Partners angemacht hat.",
"... ins Bett gekotzt.",
"... auf einer Party geweint.",
"... tagsüber im Meer Sex gehabt.",
"... Sex auf einer Strandliege gehabt.",
"... bei diesem Spiel gelogen, weil mein Partner anwesend war.",
"... wegen eines Katers auf der Arbeit kotzen müssen.",
"... meinen Intimbereich rasiert.",
"... eine Intim-Frisur gehabt für die ich mich geschämt habe.",
"... darüber nachgedacht mir Sexspielzeug zu kaufen.",
"... Liebeskugeln verwendet-",
"... während dem Telefonieren masturbiert.",
"... Sex gehabt, während mich ein Haustier beobachtet hat.",
"... darauf gewartet dass jemand anders den ersten Schritt macht.",
"... darauf gewartet, dass endlich jemand vorschlägt nackt weiter zu spielen.",
"... Wahrheit oder Pflicht gespielt.",
"... mehr als 5 mal an einem Tag masturbiert.",
"... mehr als 3 mal Sex gehabt - an einem einzigen Tag.",
"... in einer Woche jeden Tag mindestens einmal Sex gehabt.",
"... gehofft, mein Partner wäre etwas offener in Sachen Sex.",
"... eine Beziehung beendet weil der Sex nicht gut genug war.",
"... mit jemandem geflirtet, obwohl ich in einer Beziehung war.",
"... Sex gehabt während der Fernseher noch lief.",
"... Sexspielzeuge gemeinsam mit meinem Partner benutzt.",
"... meinem Partner erotische Texte geschrieben um ihn anzumachen.",
"... mit meinem Partner offen über Masturbation gesprochen.",
"... einen Tampon in der Nase stecken gehabt.",
"... Sex in der Küche gehabt.",
"... Sex auf dem Schreibtisch gehabt.",
"... vor einer größeren Gruppe blank gezogen.",
"... den Intimbereich eines Freundes / einer Freundin (gleiches Geschlecht) berührt.",
"... noch vor dem Frühstück Geschlechtsverkehr gehabt.",
"... gesagt bekommen ich sei zu schnell gekommen.",
"... für jemanden gekocht.",
"... Sex in einem Schlafsack gehabt.",
"... zugeben müssen, dass ich noch Jungfrau bin.",
"... eine versaute App auf dem Smartphone gehabt.",
"... Geld oder Geschenke für sexuelle Dienste erhalten.",
"... Bodypainting gemacht.",
"... ein Tier gemobbt.",
"... gepopelt und es dann gegessen.",
"... geniest und die Hand an jemand anderem abgewischt.",
"... einen Porno geguckt.",
"... auf meine beste/n Freund/in gestanden.",
"... einen Autounfall gehabt.",
"... Gruppensex gehabt.",
"... mit meinem Partner geschlafen, nur weil er es wollte.",
"... beim Rummachen mit meinem Partner an jemand anderen gedacht.",
"... Sex im Schwimmbad gehabt.",
"... ohne Verhütung mit jemand fremden geschlafen.",
"... mit meinem Partner ohne Verhütung geschlafen.",
"... einen Schwangerschaftstest gemacht.",
"... etwas aus dem Supermarkt gestohlen.",
"... im Club rumgemacht.",
"... im Club einen geblasen bekommen / jemandem einen geblasen.",
"... bei einer Hausparty etwas kaputt gemacht.",
"... Sex an meinem Arbeitsplatz gehabt.",
"... wegen zu viel Alkohol mit einem Fremden rumgemacht.",
"... ich habe noch nie getrunken.",
"... Sex an einem Öffentlichen Ort gehabt.",
"... Sex gehabt.",
"... den Freund / die Freundin meiner besten Freundin / meines besten Freundes geküsst.",
"... in eine Flasche gepinkelt.",
"... beim Sex meinen Freund oder Freundin angekotzt.",
"... Ananassaft getrunken, damit das Sperma besser schmeckt.",
"... mich in meine beste Freundin/besten Freund verliebt.",
"... in einem Club mit mehr als Personen rumgemacht.",
"... nach einem Horrorfilm das ganze Haus abgesucht.",
"... daran gedacht auszuwandern.",
"... jemanden aufgrund seines Aussehens ausgelacht.",
"... Unterwäsche vom anderen Geschlecht getragen. ",
"... versucht betrunken auf einen Baum zu klettern.",
"... an meinen Nägeln gekaut.",
"... verschlafen.",
"... Socken zweimal hintereinander angezogen.",
"... Erbrochenes weggemacht.",
"... einen Pickel ausgedrückt.",
"... mehr als 10 Minuten auf der Toilette verbracht.",
"... meinen Ausweis verloren.",
"... einen Penis gesehen.",
"... meinen Partner beim Sex verletzt.",
"... im Club Sex gehabt.",
"... in einem Bett mit mehr als einer nackten Person gelegen.",
"... meinen besten Freund geküsst.",
"... versucht meinen Ellbogen zu lecken. ",
"... bei diesem Spiel gelogen.",
"... mein Handy verloren.",
"... ein hormonelles Verhütungsmittel zu mir genommen.",
"... einer Person gesagt das ich sie liebe.",
"... jemandem zum Geschlechtsverkehr gezwungen.",
"... davon getr?umt, ein Charakter aus einem Buch/Film zu sein.",
"... heimlich den Alkohol meiner Eltern getrunken.",
"... eine Erektion gesehen.",
"... bei einem Film geweint.",
"... ein Kondom in der Hand gehabt.",
"... nackt im Meer/See gebadet.",
"... nach dem Sport nicht geduscht.",
"... mehr als 3 Stellungen bei einem Akt ausprobiert.",
"... Geschlechtsverkehr im Flugzeug gehabt.",
"... nie Sex auf einem Trampolin gehabt.",
"... versucht mit meinem Partner einen Porno nachzuspielen.",
"... in einem Parkhaus sexuelle Aktivitäten vollzogen.",
"... die Eltern einer Freundin/eines Freundes beim Sex gehört.",
"... Sex während einer Party gehabt.",
"... mit zwei oder mehreren Personen an einem Abend rumgerknutscht.",
"... mit jemanden rumgemacht, der in einer festen Beziehung war.",
"... Obst oder Gemüse als Sexspielzeug benutzt.",
"... die Sachen meines Partners angezogen.",
"... ein befreundetes Pärchen gefragt ob sie einen Vierer machen wollen.",
"... die Polizei um Hilfe gebeten.",
"... eine Freundschaft mit gewissen Vorzügen geführt.",
"... meinem Partner Anweisungen im Bett gegeben.",
"... im Wald masturbiert.",
"... Sex auf einer Waschmaschine gehabt.",
"... auf der Toilette telefoniert.",
"... geraucht.",
"... an einem anderen Ort als im Bett Sex gehabt.",
"... eine schlechte Schulnote vor meinen Eltern verheimlicht.",
"... mit meinen Eltern über meine Sexualität gesprochen.",
"... die Pille danach genommen.",
"... eine Zimmerpflanze vertrocknen lassen.",
"... ein Selfie gemacht.",
"... einen meiner Mitspieler nackt gesehen.",
"... Sex mit einer Person gehabt, die nicht meinem Typus entsprach, nur um Sex zu haben.",
"... jemanden ausgezogen während er schlief.",
"... mit jemandem Schluss gemacht.",
"... Gefühle für eine Person aus meiner Klasse gehabt.",
"... versucht vor der Polizei wegzulaufen.",
"... in der Dusche gesungen.",
"... nachts nackt gebadet.",
"... nachts in einem Fluss gebadet.",
"... mehr als 3 Tage im Krankenhaus verbracht.",
"... den Freund einer meiner Freundeninnen geliebt.",
"... im Bikini Autos gewaschen.",
"... eine Sex-Beziehung geführt.",
"... einen Sextraum gehabt.",
"... eine Bong geraucht.",
"... jemandem einen runtergeholt.",
"... meinem Partner mehr als 4 Orgasmen während eines Liebesaktes bereitet.",
"... Sex vor anderen Menschen gehabt.",
"... dar?ber nachgedacht, wie einer der Mitspieler nackt aussieht.",
"... mit jemandem geschlafen um an jemand anderen heran zukommen.",
"... einen Tanga getragen.",
"... eine Straftat begangen.",
"... das Bedürfnis gehabt einen Menschen zu töten.",
"... Urlaub mit Freunden gemacht.",
"... meine Eltern beleidigt.",
"... etwas mit jemanden in diesem Raum gehabt.",
"... Sex in oder an einem See gehabt.",
"... in einem Flugzeug gesessen.",
"... an einer Ferienfreizeit teilgenommen.",
"... jemanden nach seiner Nummer gefragt.",
"... einen Baum umarmt.",
"... einen Vorschlag für die App abgeschickt.",
"... mit jemandem aus meinem Freundeskreis Sex gehabt.",
"... Krokodilfleisch gegessen.",
"... meinem Partner etwas verheimlicht.",
"... Handschellen beim Sex benutzt",
"... einen Vorgesetzten/Lehrer/Chef so laut beleidigt, dass er es gehört hat.",
"... mit meiner besten Freundin rumgemacht",
"... etwas aus dem Bauchnabel eines anderen getrunken.",
"... eine Glatze gehabt.",
"... eine Beziehung gehabt, die k?rzer als 2 Wochen andauerte.",
"",
]






